/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import dao.CelularDao;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Celular;

/**
 *
 * @author Tony
 */
public class FrmCelularConsultaRapida extends javax.swing.JDialog {

    /**
     * @return the codigoCelular
     */
    public int getCodigoCelular() {
        return codigoCelular;
    }

    /**
     * @param codigoCelular the codigoCelular to set
     */
    public void setCodigoCelular(int codigoCelular) {
        this.codigoCelular = codigoCelular;
    }

    DefaultTableModel modeloTabela;
    CelularDao celularDao = new CelularDao();

    /**
     * Creates new form FrmFuncionarioConsultaRapida
     */
    public FrmCelularConsultaRapida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modeloTabela = (DefaultTableModel) grelha.getModel();
        carregaPesquisa();
    }

    // PESQUISA AVANÇADA DE FUNCIONARIOS ///////////////////////////////////////
    private void carregaPesquisa() {
        String tipoPesquisa = "";
        if (radSerie.isSelected()) {
            tipoPesquisa = "celular.serie";
        } else if (radImei.isSelected()) {
            tipoPesquisa = "celular.imei1";
        } else if (radPatrimonio.isSelected()) {
            tipoPesquisa = "celular.patrimonio";
        }

        List<Celular> listagem = celularDao.getListagemLikeAtivos(txtPesquisa.getText().trim(), tipoPesquisa);
        modeloTabela.setNumRows(0);
        for (Celular celular : listagem) {
            modeloTabela.addRow(new Object[]{
                celular.getIdCelular(),
                celular.getSerie(),
                celular.getImei1(),
                celular.getPatrimonio(),
                celular.getMarca().getMarca(),
                celular.getStatus(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        grelha = new javax.swing.JTable();
        btnOk = new javax.swing.JButton();
        radSerie = new javax.swing.JRadioButton();
        radImei = new javax.swing.JRadioButton();
        radPatrimonio = new javax.swing.JRadioButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.inactiveCaption);

        lblTitulo.setBackground(new java.awt.Color(0, 102, 102));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/celulares.png"))); // NOI18N
        lblTitulo.setText("Consulta Rápida de CELULARES");
        lblTitulo.setToolTipText("");
        lblTitulo.setOpaque(true);

        jLabel1.setText("Pesquisar:");

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        grelha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERIE", "IMEI", "PATRIMONIO", "MARCA", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grelha.setRowHeight(20);
        grelha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grelhaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grelha);
        if (grelha.getColumnModel().getColumnCount() > 0) {
            grelha.getColumnModel().getColumn(0).setPreferredWidth(30);
            grelha.getColumnModel().getColumn(0).setMaxWidth(30);
            grelha.getColumnModel().getColumn(1).setPreferredWidth(120);
            grelha.getColumnModel().getColumn(1).setMaxWidth(120);
            grelha.getColumnModel().getColumn(2).setPreferredWidth(120);
            grelha.getColumnModel().getColumn(2).setMaxWidth(120);
            grelha.getColumnModel().getColumn(3).setPreferredWidth(110);
            grelha.getColumnModel().getColumn(3).setMaxWidth(110);
            grelha.getColumnModel().getColumn(5).setPreferredWidth(80);
            grelha.getColumnModel().getColumn(5).setMaxWidth(80);
        }

        btnOk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/ok.png"))); // NOI18N
        btnOk.setText("Selecionar");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        buttonGroup1.add(radSerie);
        radSerie.setSelected(true);
        radSerie.setText("Série");
        radSerie.setOpaque(false);

        buttonGroup1.add(radImei);
        radImei.setText("IMEI");
        radImei.setOpaque(false);

        buttonGroup1.add(radPatrimonio);
        radPatrimonio.setText("Patrimônio");
        radPatrimonio.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radSerie)
                        .addGap(2, 2, 2)
                        .addComponent(radImei)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radPatrimonio)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radSerie)
                        .addComponent(radImei)
                        .addComponent(radPatrimonio))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        // TODO add your handling code here:
        carregaPesquisa();
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void grelhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grelhaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() >= 1) {
            int codigo = (int) modeloTabela.getValueAt(grelha.getSelectedRow(), 0);
            this.setCodigoCelular(codigo);
            this.dispose();
        }
    }//GEN-LAST:event_grelhaMouseClicked

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = grelha.getSelectedRowCount();
        if (linhaSelecionada > 0) {
            int codigo = (int) modeloTabela.getValueAt(grelha.getSelectedRow(), 0);
            this.setCodigoCelular(codigo);
            this.dispose();
        } else {

            JOptionPane.showMessageDialog(null, "Selecione um aparelho.", null, JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
         // TODO add your handling code here:
           if (evt.getKeyCode() == KeyEvent.VK_ENTER) {          
            if (grelha.getRowCount() == 1) {
                int codigo = (int) modeloTabela.getValueAt(0, 0);
                this.setCodigoCelular(codigo);
                this.dispose();
            }
        }
    }//GEN-LAST:event_txtPesquisaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCelularConsultaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCelularConsultaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCelularConsultaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCelularConsultaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCelularConsultaRapida dialog = new FrmCelularConsultaRapida(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private int codigoCelular;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable grelha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton radImei;
    private javax.swing.JRadioButton radPatrimonio;
    private javax.swing.JRadioButton radSerie;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
