/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulario;

import dao.CobrancaoDao;
import dao.LogDao;
import dao.UsuarioDao;
import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.TimeUnit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.Cobranca;
import modelo.Emprestimo;
import modelo.Session;
import modelo.Usuario;
import utilidade.EnviarEmail;

/**
 *
 * @author otoniel.aalves
 */
public class FrmCobrancaEmail extends javax.swing.JFrame {

    /**
     * Creates new form FrmCobrancaEmail
     */
    CobrancaoDao cobrancaoDao = new CobrancaoDao();

    Cobranca cobranca = null;
    LogDao logDao = new LogDao();

    String protocolo;

    Usuario usuarioLogado = new UsuarioDao().getPorID(Session.getIdUsuario());

    EnviarEmail enviarEmail = new EnviarEmail();

    public FrmCobrancaEmail() {

        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        carregaGrelha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCobranca = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnTodo1 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnTodo3 = new javax.swing.JButton();
        ckPendente = new javax.swing.JCheckBox();
        ckFinalizado = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        btnMarcarPendente = new javax.swing.JButton();
        btnPesquisaRapida = new javax.swing.JButton();
        txtQuantidade = new javax.swing.JLabel();
        ckTodos = new javax.swing.JCheckBox();
        ckVerTodos = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        lblTitulo.setBackground(new java.awt.Color(0, 51, 0));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cobrança de Assinaturas de Protocolos");
        lblTitulo.setToolTipText("");
        lblTitulo.setOpaque(true);

        tabelaCobranca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Data", "Protocolo", "Funcionário", "Email", "Localidade", "Motivo", "Situacao", "Qtde", "Último Envio", "Responsável Envio", "True"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCobranca.setRowHeight(23);
        tabelaCobranca.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane1.setViewportView(tabelaCobranca);
        if (tabelaCobranca.getColumnModel().getColumnCount() > 0) {
            tabelaCobranca.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabelaCobranca.getColumnModel().getColumn(0).setMaxWidth(100);
            tabelaCobranca.getColumnModel().getColumn(1).setPreferredWidth(100);
            tabelaCobranca.getColumnModel().getColumn(1).setMaxWidth(100);
            tabelaCobranca.getColumnModel().getColumn(2).setPreferredWidth(160);
            tabelaCobranca.getColumnModel().getColumn(2).setMaxWidth(160);
            tabelaCobranca.getColumnModel().getColumn(4).setPreferredWidth(400);
            tabelaCobranca.getColumnModel().getColumn(4).setMaxWidth(400);
            tabelaCobranca.getColumnModel().getColumn(7).setPreferredWidth(150);
            tabelaCobranca.getColumnModel().getColumn(7).setMaxWidth(150);
            tabelaCobranca.getColumnModel().getColumn(8).setPreferredWidth(60);
            tabelaCobranca.getColumnModel().getColumn(8).setMaxWidth(60);
            tabelaCobranca.getColumnModel().getColumn(9).setPreferredWidth(150);
            tabelaCobranca.getColumnModel().getColumn(9).setMaxWidth(150);
            tabelaCobranca.getColumnModel().getColumn(11).setPreferredWidth(50);
            tabelaCobranca.getColumnModel().getColumn(11).setMaxWidth(50);
        }

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Pesquisar por PROTOCOLO ou NOME:");

        btnTodo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTodo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/send-emailResultado.png"))); // NOI18N
        btnTodo1.setText("Enviar Email");
        btnTodo1.setToolTipText("Enviar para todos");
        btnTodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodo1ActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 204, 204));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cross.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Excluir das cobranças");
        btnExcluir.setMinimumSize(new java.awt.Dimension(89, 33));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnTodo3.setBackground(new java.awt.Color(255, 255, 204));
        btnTodo3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTodo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/ok.png"))); // NOI18N
        btnTodo3.setText("Marcar FINALIZADO");
        btnTodo3.setToolTipText("Marcar OK");
        btnTodo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodo3ActionPerformed(evt);
            }
        });

        ckPendente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ckPendente.setForeground(new java.awt.Color(0, 102, 51));
        ckPendente.setSelected(true);
        ckPendente.setText("PENDENTES");
        ckPendente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckPendenteMouseClicked(evt);
            }
        });

        ckFinalizado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ckFinalizado.setForeground(new java.awt.Color(153, 51, 0));
        ckFinalizado.setText("FINALIZADOS");
        ckFinalizado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckFinalizadoMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lupa.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.setToolTipText("Buscar por filtro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnMarcarPendente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMarcarPendente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/edit.png"))); // NOI18N
        btnMarcarPendente.setText("Marcar PENDENTE");
        btnMarcarPendente.setToolTipText("Marcar PENDENTE");
        btnMarcarPendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarPendenteActionPerformed(evt);
            }
        });

        btnPesquisaRapida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lupa.png"))); // NOI18N
        btnPesquisaRapida.setToolTipText("Pesquisa rápida de protocolo");
        btnPesquisaRapida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaRapidaActionPerformed(evt);
            }
        });

        txtQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtQuantidade.setText("Quantidade: 0");

        ckTodos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ckTodos.setText("Todos");
        ckTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckTodosActionPerformed(evt);
            }
        });

        ckVerTodos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ckVerTodos.setText("Ver todos");
        ckVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckVerTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ckPendente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckFinalizado)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckTodos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMarcarPendente, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTodo3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisaRapida, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckVerTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 451, Short.MAX_VALUE)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckPendente)
                            .addComponent(ckFinalizado)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckTodos)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMarcarPendente, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTodo3, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaRapida, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnTodo1)
                    .addComponent(ckVerTodos))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:        
        excluir();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnTodo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodo3ActionPerformed
        // TODO add your handling code here:
        marcarOK();
    }//GEN-LAST:event_btnTodo3ActionPerformed

    private void btnTodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodo1ActionPerformed
        // TODO add your handling code here:

        //enviarEmailTodos();
        enviarEmailTodosGpt();

    }//GEN-LAST:event_btnTodo1ActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        // TODO add your handling code here:
        carregaGrelha();
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        carregaGrelha();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnMarcarPendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarPendenteActionPerformed
        // TODO add your handling code here:
        marcarPendente();
    }//GEN-LAST:event_btnMarcarPendenteActionPerformed

    private void btnPesquisaRapidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaRapidaActionPerformed
        // TODO add your handling code here:

        FrmEmprestimoConsultaRapida frm = new FrmEmprestimoConsultaRapida(this, true);
        frm.setVisible(true);

        Emprestimo emprestimo = frm.getEmprestimo();

        if (emprestimo != null) {

            // Verifica se a pessoa tem email cadastrado
            if (emprestimo.getFuncionario().getEmail() == null || emprestimo.getFuncionario().getEmail().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Funcionário NÃO tem EMAIL cadastrado no sistema.", null, JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Verifica se tem protocolo cadastrado na listagem
            if (cobrancaoDao.verificaJaCadastradoPorProtocoloPendentes(emprestimo.getProtocolo())) {
                JOptionPane.showMessageDialog(this, emprestimo.getProtocolo() + " - Protocolo já consta na listagem.", null, JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Verifica se tem protocolo cadastrado
            String protocoloSemPonto = emprestimo.getProtocolo().replace(".", "").replace("-", "");

            if (protocoloSemPonto.equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, protocoloSemPonto + " - Não consta PROTOCOLO no cadastro.", null, JOptionPane.ERROR_MESSAGE);
                return;
            }

            int resposta = JOptionPane.showConfirmDialog(this, "Deseja cadastrar o protocolo: " + emprestimo.getProtocolo() + "?", null, JOptionPane.YES_NO_OPTION);

            if (resposta == JOptionPane.YES_OPTION) {

                cobranca = new Cobranca();

                // Cobranca(int idCobranca, String data, Funcionario funcionario, String protocolo, String motivo, Emprestimo emprestimo, String status, String dataEnvio, Usuario usuario, int quantidade) 
                this.cobranca.setData(hoje());
                this.cobranca.setFuncionario(emprestimo.getFuncionario());
                this.cobranca.setProtocolo(emprestimo.getProtocolo());
                this.cobranca.setMotivo(emprestimo.getCelular().getMarca().getMarca() + ", IMEI: " + emprestimo.getCelular().getImei1());

                this.cobranca.setStatus("PENDENTE");
                this.cobranca.setEmprestimo(emprestimo);
                this.cobranca.setUsuario(usuarioLogado); // Pega o usuário da sessão  

                this.cobranca.setQuantidade(0);

                cobrancaoDao.insert(cobranca);

                carregaGrelha();
                JOptionPane.showMessageDialog(this, "Cadastrado com Sucesso.", null, JOptionPane.INFORMATION_MESSAGE);

            } else if (resposta == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(this, "Operação Cancelada.", null, JOptionPane.INFORMATION_MESSAGE);
            }

        }


    }//GEN-LAST:event_btnPesquisaRapidaActionPerformed

    private void ckFinalizadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckFinalizadoMouseClicked
        // TODO add your handling code here:
        carregaGrelha();
    }//GEN-LAST:event_ckFinalizadoMouseClicked

    private void ckPendenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckPendenteMouseClicked
        // TODO add your handling code here:
        carregaGrelha();
    }//GEN-LAST:event_ckPendenteMouseClicked

    private void ckTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckTodosActionPerformed
        // TODO add your handling code here:

        if (ckTodos.isSelected()) {
            marcarCaixa(true);
        } else {
            marcarCaixa(false);
        }

    }//GEN-LAST:event_ckTodosActionPerformed

    private void ckVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckVerTodosActionPerformed
        // TODO add your handling code here:
        if (ckVerTodos.isSelected()) {
            carregaGrelha();
        } else {
            carregaGrelha();
        }
    }//GEN-LAST:event_ckVerTodosActionPerformed

    private void marcarCaixa(boolean valor) {
        int linha = 11;

        for (int i = 0; i < tabelaCobranca.getRowCount(); i++) {
            tabelaCobranca.setValueAt(valor, i, linha);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCobrancaEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCobrancaEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCobrancaEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCobrancaEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCobrancaEmail().setVisible(true);
            }
        });
    }

    //CARREGA GRELHA OTIMIZADA-------------------------------------------------
    public final void carregaGrelha() {

        DefaultTableModel modelo = (DefaultTableModel) tabelaCobranca.getModel();
        modelo.setNumRows(0);
        int ckBusca = 1;
        int id_responsavel = Session.getIdUsuario();

        if (!ckPendente.isSelected() && !ckFinalizado.isSelected()) {
            ckPendente.setSelected(true);
        }

        if (ckPendente.isSelected() && !ckFinalizado.isSelected()) {
            ckBusca = 1;
        }

        if (!ckPendente.isSelected() && ckFinalizado.isSelected()) {
            ckBusca = 2;
        }

        if (ckPendente.isSelected() && ckFinalizado.isSelected()) {
            ckBusca = 3;
        }

        // Validar ver todos
        if (ckVerTodos.isSelected()) {
            id_responsavel = 0;
        }

        List<Cobranca> lista = cobrancaoDao.getListagemCobrancasAlls(ckBusca, txtPesquisa.getText(), id_responsavel);

        for (Cobranca cobranca : lista) {

            modelo.addRow(new Object[]{
                cobranca.getIdCobranca(),
                cobranca.getData(),
                cobranca.getProtocolo(),
                cobranca.getFuncionario().getNome(),
                cobranca.getFuncionario().getEmail(),
                cobranca.getFuncionario().getLocalidade().getNomeLocalidade(),
                cobranca.getMotivo(),
                cobranca.getStatus(),
                cobranca.getQuantidade(),
                cobranca.getDataEnvio(),
                cobranca.getUsuarioEnvio().getNome(),
                false,});
        }

        txtQuantidade.setText("Quantidade: " + lista.size());

        pinta();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnMarcarPendente;
    private javax.swing.JButton btnPesquisaRapida;
    private javax.swing.JButton btnTodo1;
    private javax.swing.JButton btnTodo3;
    private javax.swing.JCheckBox ckFinalizado;
    private javax.swing.JCheckBox ckPendente;
    private javax.swing.JCheckBox ckTodos;
    private javax.swing.JCheckBox ckVerTodos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tabelaCobranca;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JLabel txtQuantidade;
    // End of variables declaration//GEN-END:variables

    /* 
    Função exclusão de item de listagem
    Apenas administrador de sistema  
     */
    private void excluir() {

        // Verifica o previlégio do usuario
        if (Session.getPrevilegio().equals("Consulta")) {
            JOptionPane.showMessageDialog(this, "Usuário se permissão para exclusão.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Verifica se foi selecionado uma linha
        if (tabelaCobranca.getSelectedRowCount() <= 0) {
            JOptionPane.showMessageDialog(null, "Selecione um linha para exclusão.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        int resposta, idCobranca, linha;

        linha = tabelaCobranca.getSelectedRow(); // Qual foi a linha
        String nome = (String) tabelaCobranca.getValueAt(linha, 3); // Pego o numero do protocolo

        resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o registro: " + nome + " ?", "Escolha um", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {

            idCobranca = (int) tabelaCobranca.getValueAt(linha, 0); // Pego o id selecionado
            this.protocolo = (String) tabelaCobranca.getValueAt(linha, 2); // Pego o numero do protocolo

            cobrancaoDao.delete(idCobranca);
            logDao.insert("Excluído cobrança do protocolo: " + protocolo);
            JOptionPane.showMessageDialog(this, "Excluído com Sucesso.", null, JOptionPane.INFORMATION_MESSAGE);

            carregaGrelha();

        } else if (resposta == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Operação Cancelada.", null, JOptionPane.INFORMATION_MESSAGE);
        }

    }

    /* 
    Função que marca como assinado com sucesso 
     */
    private void marcarOK() {

        // Verifica o previlégio do usuario
        if (Session.getPrevilegio().equals("Consulta")) {
            JOptionPane.showMessageDialog(this, "Usuário se permissão para exclusão.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Verifica se foi selecionado uma linha
        if (tabelaCobranca.getSelectedRowCount() <= 0) {
            JOptionPane.showMessageDialog(null, "Selecione um linha.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        int linha = tabelaCobranca.getSelectedRow(); // Qual foi a linha
        int idCobranca = (int) tabelaCobranca.getValueAt(linha, 0); // Pego o id selecionado
        this.protocolo = (String) tabelaCobranca.getValueAt(linha, 2); // Pego o numero do protocolo

        int resposta;

        resposta = JOptionPane.showConfirmDialog(this, "Deseja FINALIAZAR o protocolo: " + this.protocolo + " ?", "Escolha um", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {

            cobrancaoDao.marcarFinalizado(idCobranca);

            logDao.insert("Protocolo finalizado de cobrança: " + protocolo);

            JOptionPane.showMessageDialog(this, "OK Finalizado como sucesso.", null, JOptionPane.INFORMATION_MESSAGE);

            carregaGrelha();

        } else if (resposta == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Operação Cancelada.", null, JOptionPane.INFORMATION_MESSAGE);
        }

    }

    private void marcarPendente() {

        // Verifica o previlégio do usuario
        if (Session.getPrevilegio().equals("Consulta")) {
            JOptionPane.showMessageDialog(this, "Usuário se permissão para exclusão.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Verifica se foi selecionado uma linha
        if (tabelaCobranca.getSelectedRowCount() <= 0) {
            JOptionPane.showMessageDialog(null, "Selecione um linha.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        int linha = tabelaCobranca.getSelectedRow(); // Qual foi a linha
        this.protocolo = (String) tabelaCobranca.getValueAt(linha, 2); // Pego o numero do protocolo

        int resposta;

        resposta = JOptionPane.showConfirmDialog(this, "Deseja deixar PENDENTE o protocolo - " + this.protocolo + " ?", "Escolha um", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {

            int idCobranca = (int) tabelaCobranca.getValueAt(linha, 0); // Pego o id selecionado

            cobrancaoDao.marcarReaberto(idCobranca);

            logDao.insert("Protocolo reaberto de cobrança: " + protocolo);

            JOptionPane.showMessageDialog(this, "OK Reaberto como sucesso.", null, JOptionPane.INFORMATION_MESSAGE);

            carregaGrelha();

        } else if (resposta == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Operação Cancelada.", null, JOptionPane.INFORMATION_MESSAGE);
        }

    }

    // FUNCÃO DATA HOJE ////////////////////////////////////////////////////////F
    private String hoje() {
        return new SimpleDateFormat("dd/MM/yyyy").format(new Date());
    }

//    /*
//    Envia email para uma pessoa somente
//     */
//    private void enviarUmSelecionado() {
//
//        // Verifica o previlégio do usuario
////        if (Session.getPrevilegio().equals("Consulta")) {
////            JOptionPane.showMessageDialog(this, "Usuário se permissão para exclusão.", null, JOptionPane.ERROR_MESSAGE);
////            return;
////        }
//        // Verifica se foi selecionado uma linha
//        if (tabelaCobranca.getSelectedRowCount() <= 0) {
//            JOptionPane.showMessageDialog(null, "Selecione um linha.", null, JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        int resposta;
//
//        int linha = tabelaCobranca.getSelectedRow(); // Qual foi a linha
//        int idCobranca = (int) tabelaCobranca.getValueAt(linha, 0); // Pego o id selecionado  
//        String prot = (String) tabelaCobranca.getValueAt(linha, 2); // Pego o id selecionado  
//        String pessoa = (String) tabelaCobranca.getValueAt(linha, 3); // Pesso Selecionada 
//        String email = (String) tabelaCobranca.getValueAt(linha, 4); // Pesso Selecionada 
//        String pendente = (String) tabelaCobranca.getValueAt(linha, 7);
//        boolean enviar = (boolean) tabelaCobranca.getValueAt(linha, 11);
//
//        if (email == null || email.equalsIgnoreCase("")) {
//            JOptionPane.showMessageDialog(null, pessoa + " - Não tem EMAIL Cadastrado.", null, JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        if (pendente.equalsIgnoreCase("FINALIZADO")) {
//            JOptionPane.showMessageDialog(null, prot + " - Cobrança FINALIZADA, sem PENDÊNCIA.", null, JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        resposta = JOptionPane.showConfirmDialog(this, "Deseja Envial email para " + pessoa + " ?", "Escolha um", JOptionPane.YES_NO_OPTION);
//
//        if (resposta == JOptionPane.YES_OPTION) {
//
//            // Enviar email conforme a linha
//            for (int i = 0; i < tabelaCobranca.getRowCount(); i++) {
//
//                idCobranca = (int) tabelaCobranca.getValueAt(i, 0); // Pego o id selecionado
//                pendente = (String) tabelaCobranca.getValueAt(i, 7);
//
//                if (pendente.equalsIgnoreCase("PENDENTE") && enviar) {
//
//                    // Monta e Enviar o email
//                    montarEmail(i);
//
//                    // Atualiza quantidade no sistema
//                    atualizarQuantidadeEnvioEmail(idCobranca);
//
//                }
//
//            }
//
//            carregaGrelha();
//
//            JOptionPane.showMessageDialog(this, "Email enviado com sucesso.", null, JOptionPane.INFORMATION_MESSAGE);
//
//        } else if (resposta == JOptionPane.NO_OPTION) {
////////            JOptionPane.showMessageDialog(this, "Operação Cancelada.", null, JOptionPane.INFORMATION_MESSAGE);
//        }
//    }
    //////////////////////////////////////////////////////////////////////////
    //Envia email para todo de uma vez*/
    // Verificar se tem alguma linha selecionada.
    private boolean verficarMarcados() {

        for (int i = 0; i < tabelaCobranca.getRowCount(); i++) {

            System.out.println(tabelaCobranca.getValueAt(i, 11).toString());

            boolean marcado = (boolean) tabelaCobranca.getValueAt(i, 11);

            if (marcado) {
                return true;

            }
        }
        return false;
    }

    private void enviarEmailTodos() {

        // Verifica o previlégio do usuario
        if (Session.getPrevilegio().equals("Consulta")) {
            JOptionPane.showMessageDialog(this, "Usuário se permissão para exclusão.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }
//        
        if (!verficarMarcados()) {
            JOptionPane.showMessageDialog(this, "Selecione um protocolo para envio.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        int resposta;
        String pendente;
        boolean marcado;

        resposta = JOptionPane.showConfirmDialog(this, "Deseja Enviar email para TODOS ?", "Escolha um", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {

            ExecutorService executor = Executors.newFixedThreadPool(3);

            // Enviar email conforme a linha
            for (int i = 0; i < tabelaCobranca.getRowCount(); i++) {

                int linha = i;
                pendente = (String) tabelaCobranca.getValueAt(linha, 7);
                marcado = (boolean) tabelaCobranca.getValueAt(linha, 11);

                if (pendente.equalsIgnoreCase("PENDENTE") && marcado) {

                    executor.submit(() -> {

                        try {

                            enviarEmail = new EnviarEmail(); // Cria uma nova instância para envio.

                            // Pegando os dados da tabela
                            int cobranca_id = (int) tabelaCobranca.getValueAt(linha, 0); // Pego o id selecionado
                            this.protocolo = (String) tabelaCobranca.getValueAt(linha, 2); // Pego o numero do protocolo
                            String nomeFuncionario = (String) tabelaCobranca.getValueAt(linha, 3); // Pego o nome do Funcionario
                            String email = (String) tabelaCobranca.getValueAt(linha, 4); // Pego o email do Funcionário

                            //String email3 = "otoniel.aalves@detran.pr.gov.br"; // Pego o email do Funcionário
                            // Gerando o texto de envio
                            String cabecalho = "Protocolo " + this.protocolo + " com Pendência de assinatura.";

                            String texto = "<html>"
                                    + "<body style='font-family: Arial, sans-serif; font-size:12px;'>"
                                    + "Olá, <b>" + nomeFuncionario + "</b>, \n\n"
                                    + "Gostaríamos de lembrar que o protocolo [ nº <b>" + this.protocolo + "</b> ] está pendente de sua assinatura em nosso sistema. \n"
                                    + "A leitura e a concordância com essas diretrizes são essenciais para mantermos nossa equipe alinhada e nossas operações seguras. \n\n"
                                    + "Como regularizar sua pendência: \n"
                                    + "Acesse o sistema: Acessar > E-protocolo > ir em: Minhas Pendências > Selecionar a caixa de confirmação > Assinar > Assinatura avançada "
                                    + "Prazo limite: [ <b>24 horas do envio do e-mail </b> ] \n\n"
                                    + "Caso já tenha realizado a assinatura recentemente, por favor, desconsidere este e-mail. \n\n"
                                    + "Se tiver alguma dúvida sobre o conteúdo ou dificuldade de acesso, basta responder a esta mensagem ou entrar em contato via ramal " + this.usuarioLogado.getRamal() + ". \n\n"
                                    + "Agradecemos a sua colaboração. \n\n\n"
                                    + "Atenciosamente, \n\n"
                                    + this.usuarioLogado.getNome()
                                    + "</body>"
                                    + "</html>";

                            if (!email.equalsIgnoreCase("")) {

                                // Enviar o email
                                new EnviarEmail().enviar(email, cabecalho, texto);

                                // Atualiza quantidade no sistema
                                atualizarQuantidadeEnvioEmail(cobranca_id);

                                // Envia email se tem email cadastrado  
                                int valor = 1500 + ThreadLocalRandom.current().nextInt(31) * 50;
                                Thread.sleep(valor);

                            }

                        } catch (InterruptedException e) {
                            //executor.shutdownNow();
                            JOptionPane.showMessageDialog(this, "Erro ao montar o email. Erro: " + e.toString(), null, JOptionPane.ERROR_MESSAGE);
                        }

                    });

                    executor.shutdown();

                    try {

                        if (!executor.awaitTermination(30, TimeUnit.MINUTES)) {
                            JOptionPane.showMessageDialog(null, "Todos os e-mails foram processados.", null, JOptionPane.INFORMATION_MESSAGE);
                        }

                    } catch (InterruptedException e) {

                        executor.shutdownNow();
                        Thread.currentThread().interrupt();

                    }

                }

            }

            //carregaGrelha();
            //JOptionPane.showMessageDialog(this, "Emails enviados com sucesso.", null, JOptionPane.INFORMATION_MESSAGE);
        } else if (resposta == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Operação Cancelada.", null, JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void atualizarQuantidadeEnvioEmail(int idCobranca) {

        // Busca qual é a cobrança pra atualizar os dados
        cobranca = cobrancaoDao.buscaByID(idCobranca);
        cobranca.setDataEnvio(hoje());
        cobranca.setUsuarioEnvio(new Usuario(Session.getIdUsuario()));
        cobranca.setQuantidade(cobranca.getQuantidade() + 1);
        cobrancaoDao.marcarEnvioEmail(cobranca);

    }

    // PINTANDO GRADE 
    private void pinta() {

        int coluna = 7; // Qual coluna
        String finalizado = "FINALIZADO"; // O que procura

        tabelaCobranca.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                //*******************************************
                Object procurado = tabelaCobranca.getValueAt(row, coluna);

                if (procurado.equals(finalizado)) {  // Se finalizado pinta de vermelho ou preto.
                    label.setForeground(Color.RED);
                } else {
                    label.setForeground(Color.BLACK);
                }

                //*******************************************
                return label;

            }
        });
    }

    // ENVIO FUNÇÃO CORRIGIDA PELO CHAT GPT
    private void enviarEmailTodosGpt() {

        // Verifica o privilégio do usuário
        if (Session.getPrevilegio().equals("Consulta")) {
            JOptionPane.showMessageDialog(this, "Usuário sem permissão para envio.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!verficarMarcados()) {
            JOptionPane.showMessageDialog(this, "Selecione um protocolo para envio.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        int resposta = JOptionPane.showConfirmDialog(this, "Deseja enviar e-mail para TODOS?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if (resposta != JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Operação cancelada.", null, JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        
        
        

        ExecutorService executor = Executors.newFixedThreadPool(2);

        for (int i = 0; i < tabelaCobranca.getRowCount(); i++) {

            boolean marcado = (boolean) tabelaCobranca.getValueAt(i, 11);
            String pendente = (String) tabelaCobranca.getValueAt(i, 7);

            if (!marcado || !pendente.equalsIgnoreCase("PENDENTE")) {
                continue;
            }

            // Copia os dados da linha
            final int cobrancaId = (int) tabelaCobranca.getValueAt(i, 0);
            final String protocolo = (String) tabelaCobranca.getValueAt(i, 2);
            final String nomeFuncionario = (String) tabelaCobranca.getValueAt(i, 3);
            final String email = (String) tabelaCobranca.getValueAt(i, 4);
            
            final String ramalUsuario = usuarioLogado.getRamal();
            final String nomeUsuario = usuarioLogado.getNome();

            executor.submit(() -> {

                try {

                    if (email == null || email.trim().isEmpty()) {
                        return;
                    }

                    String cabecalho = "Protocolo " + protocolo + " com Pendência de Assinatura.";

                    String texto
                            = "<html>"
                            + "<body style='font-family: Arial, sans-serif; font-size:12px;'>"
                            + "Olá, <b>" + nomeFuncionario + "</b>,<br><br>"
                            + "Gostaríamos de lembrar que o protocolo nº <b>" + protocolo + "</b> está pendente de sua assinatura em nosso sistema.<br><br>"
                            + "Como regularizar sua pendência:<br>"
                            + "Acesse o sistema: <strong>E-Protocolo → Minhas Pendências → Selecione a confirmação → Assinar → Assinatura avançada.</strong><br><br>"
                            + "<b>Prazo: 24 horas após o envio deste e-mail.</b><br><br>"
                            + "Caso já tenha realizado a assinatura, desconsidere esta mensagem.<br><br>"
                            + "Dúvidas, entre em contato pelo ramal <strong>"
                            + ramalUsuario
                            + "</strong>.<br><br>"
                            + "Atenciosamente,<br><br>"
                            + nomeUsuario
                            + "</body></html>";

                   
                    new EnviarEmail().enviar(email, cabecalho, texto);

                    atualizarQuantidadeEnvioEmail(cobrancaId);

                    // Mostra no console quem foi enviado
                    System.out.println("Enviado para: " + email);

                    Thread.sleep(1500 + ThreadLocalRandom.current().nextInt(1500));

                } catch (InterruptedException ex) {

                    SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(null, "Erro ao enviar para " + email + "\nErro:" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE));

                }

            });

        }

        // Mensagem imediatamente
        JOptionPane.showMessageDialog(this, "Todos os e-mails foram enviados com sucesso.", "Finalizado", JOptionPane.INFORMATION_MESSAGE);

        // Thread que espera terminar
        new Thread(() -> {

            executor.shutdown();

            try {

                executor.awaitTermination(30, TimeUnit.MINUTES);

                SwingUtilities.invokeLater(() -> {

                    carregaGrelha();
                    //JOptionPane.showMessageDialog(this, "Todos os e-mails foram enviados com sucesso.", "Finalizado", JOptionPane.INFORMATION_MESSAGE);

                });

            } catch (InterruptedException ex) {

                executor.shutdownNow();
                Thread.currentThread().interrupt();

            }

        }).start();

    }
}
