/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import dao.AcessorioDao;
import dao.CelularDao;
import dao.ChipDao;
import dao.EmprestimoDao;
import dao.ImpressaoDao;
import java.awt.Color;
import java.awt.Component;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JLabel;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

import javax.swing.table.DefaultTableModel;
import modelo.Acessorio;
import modelo.Celular;
import modelo.Chip;
import modelo.Emprestimo;

/**
 *
 * @author Tony
 */
public class FrmEmprestimoConsulta extends javax.swing.JFrame {

    EmprestimoDao emprestimoDao = new EmprestimoDao();
    DefaultTableModel modeloGrelha;
    ImpressaoDao imprimir = new ImpressaoDao();

    /**
     * Creates new form FrmEmprestimoConsulta
     */
    public FrmEmprestimoConsulta() {
        initComponents();
        modeloGrelha = (DefaultTableModel) grelhaEmprestimo.getModel();
        carregarGrelha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        radNome = new javax.swing.JRadioButton();
        radImei = new javax.swing.JRadioButton();
        radLinha = new javax.swing.JRadioButton();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        grelhaEmprestimo = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        ckDevolvidos = new javax.swing.JCheckBox();
        btnReemitir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(222, 231, 248));

        lblTitulo.setBackground(new java.awt.Color(0, 51, 102));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Consulta  de Emprestimos");
        lblTitulo.setToolTipText("");
        lblTitulo.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Seleciona Pesquisa:");

        buttonGroup1.add(radNome);
        radNome.setSelected(true);
        radNome.setText("Nome");
        radNome.setOpaque(false);

        buttonGroup1.add(radImei);
        radImei.setText("Imei");
        radImei.setOpaque(false);

        buttonGroup1.add(radLinha);
        radLinha.setText("Nª da Linha ");
        radLinha.setOpaque(false);

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        grelhaEmprestimo.setAutoCreateRowSorter(true);
        grelhaEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nª TERMO", "DATA", "SITUAÇÃO", "FUNCIONÁRIO", "SETOR", "APARELHO", "IMEI", "Nª TELEFONE", "DADOS", "VOZ", "PROTOCOLO", "DEVOLUÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grelhaEmprestimo.setRowHeight(21);
        grelhaEmprestimo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(grelhaEmprestimo);
        if (grelhaEmprestimo.getColumnModel().getColumnCount() > 0) {
            grelhaEmprestimo.getColumnModel().getColumn(0).setPreferredWidth(70);
            grelhaEmprestimo.getColumnModel().getColumn(0).setMaxWidth(70);
            grelhaEmprestimo.getColumnModel().getColumn(1).setPreferredWidth(80);
            grelhaEmprestimo.getColumnModel().getColumn(1).setMaxWidth(80);
            grelhaEmprestimo.getColumnModel().getColumn(2).setPreferredWidth(90);
            grelhaEmprestimo.getColumnModel().getColumn(2).setMaxWidth(90);
            grelhaEmprestimo.getColumnModel().getColumn(3).setPreferredWidth(250);
            grelhaEmprestimo.getColumnModel().getColumn(3).setMaxWidth(250);
            grelhaEmprestimo.getColumnModel().getColumn(4).setPreferredWidth(180);
            grelhaEmprestimo.getColumnModel().getColumn(4).setMaxWidth(180);
            grelhaEmprestimo.getColumnModel().getColumn(5).setPreferredWidth(180);
            grelhaEmprestimo.getColumnModel().getColumn(5).setMaxWidth(180);
            grelhaEmprestimo.getColumnModel().getColumn(8).setPreferredWidth(60);
            grelhaEmprestimo.getColumnModel().getColumn(8).setMaxWidth(60);
            grelhaEmprestimo.getColumnModel().getColumn(9).setPreferredWidth(60);
            grelhaEmprestimo.getColumnModel().getColumn(9).setMaxWidth(60);
        }

        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/new.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/edit.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnDevolver.setBackground(new java.awt.Color(255, 204, 204));
        btnDevolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/devolver.png"))); // NOI18N
        btnDevolver.setText("Devolução de Emprestimo");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        ckDevolvidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckDevolvidos.setForeground(new java.awt.Color(153, 0, 0));
        ckDevolvidos.setText("MOSTRA DEVOLVIDOS");
        ckDevolvidos.setOpaque(false);
        ckDevolvidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckDevolvidosActionPerformed(evt);
            }
        });

        btnReemitir.setBackground(new java.awt.Color(255, 204, 153));
        btnReemitir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReemitir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/impressora.png"))); // NOI18N
        btnReemitir.setText("Reemitir Termo");
        btnReemitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReemitirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReemitir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 846, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(radNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radImei)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radLinha)
                        .addGap(18, 18, 18)
                        .addComponent(ckDevolvidos)
                        .addGap(33, 33, 33)
                        .addComponent(txtPesquisa)))
                .addContainerGap())
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(radNome)
                    .addComponent(radImei)
                    .addComponent(radLinha)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckDevolvidos))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnReemitir)
                    .addComponent(btnDevolver))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        FrmEmprestimo frm = new FrmEmprestimo(this, false);
        frm.novo = true;
        frm.setVisible(true);

    }//GEN-LAST:event_btnNovoActionPerformed

    // CARREGA GRELHA CONFORME PESQUISA ////////////////////////////////////////
    private void carregarGrelha() {
        // pesquisa somente emprestados
        String soEmprestados = "", tipoPesquisa;

        if (radNome.isSelected()) {
            tipoPesquisa = "nome";
        } else if (radImei.isSelected()) {
            tipoPesquisa = "imei";
        } else {
            tipoPesquisa = "linha";
        }

        if (!ckDevolvidos.isSelected()) {
            soEmprestados = "EMPRESTADO";
        }

        ArrayList<Emprestimo> lista = emprestimoDao.getListagemLike(txtPesquisa.getText(), soEmprestados, tipoPesquisa);
        modeloGrelha.setNumRows(0);

        //System.out.println(lista.size());
        lista.forEach((emprestimo) -> {

            String dados;
            String voz;

            if (emprestimo.getChip().isIsDado()) {
                dados = "Internet";
            } else {
                dados = "";
            }
            if (emprestimo.getChip().isIsTelefonia()) {
                voz = "Voz";
            } else {
                voz = "";
            }

            modeloGrelha.addRow(new Object[]{
                emprestimo.getIdEmprestimo(),
                emprestimo.getDataEmprestimo(),
                emprestimo.getSituacao(),
                emprestimo.getFuncionario().getNome(),
                emprestimo.getFuncionario().getLocalidade().getNomeLocalidade(),
                emprestimo.getCelular().getMarca().getMarca(),
                emprestimo.getCelular().getImei1(),
                emprestimo.getChip().getNumeroLinha(),
                dados,
                voz,
                emprestimo.getProtocolo(),
                emprestimo.getDataDevolucao(),}
            );

            pinta();
        });

    }

    // PINTANDO GRADE 
    private void pinta() {
        grelhaEmprestimo.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                //*******************************************
                int coluna = 2;
                Object procurado = grelhaEmprestimo.getValueAt(row, coluna);

                if (procurado.equals("EMPRESTADO")) {
                    label.setForeground(Color.BLACK);
                } else {
                    label.setForeground(Color.RED);
                }

                //*******************************************
                return label;

            }
        });
    }


    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:

        if (grelhaEmprestimo.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um Equipamento para Alteração.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        String devolvido = (String) grelhaEmprestimo.getValueAt(grelhaEmprestimo.getSelectedRow(), 2);
        if (devolvido.equalsIgnoreCase("DEVOLVIDO")) {
            JOptionPane.showMessageDialog(null, "Situação DEVOLVIDO não permite alteração.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        int codigo = (int) grelhaEmprestimo.getValueAt(grelhaEmprestimo.getSelectedRow(), 0);
        FrmEmprestimo frm = new FrmEmprestimo(this, false);
        frm.novo = false;
        frm.emprestimo_id = codigo;
        frm.setVisible(true);


    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        // TODO add your handling code here:
        carregarGrelha();
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:

        if (grelhaEmprestimo.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um Equipamento para Excluír.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        String devolvido = (String) grelhaEmprestimo.getValueAt(grelhaEmprestimo.getSelectedRow(), 2);
        if (devolvido.equalsIgnoreCase("EMPRESTADO")) {
            JOptionPane.showMessageDialog(null, "Situação EMPRESTADO não pode exclusão.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        int resposta;
        resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Escolha um", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {

            int codigo = (int) grelhaEmprestimo.getValueAt(grelhaEmprestimo.getSelectedRow(), 0);
            Emprestimo emprestimo = emprestimoDao.retornaPorID(codigo);
            //DEVOLVE O CHIP
            Chip chip = new Chip(emprestimo.getChip().getIdChip());
            chip.setStatus("Ativo");
            new ChipDao().updateStatus(chip);
            // DEVOLVE O CELULAR
            Celular celular = new Celular(emprestimo.getCelular().getIdCelular());
            celular.setStatus("Ativo");
            new CelularDao().updateStatus(celular);
            // APAGUA O EMPRESTIMO
            new EmprestimoDao().deleteUmItem(emprestimo.getIdEmprestimo());
            JOptionPane.showMessageDialog(null, "Excluído com Sucesso.");
            carregarGrelha();

        } else if (resposta == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Operação Cancelada.", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        // TODO add your handling code here:
        if (grelhaEmprestimo.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um Equipamento para Alteração.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        String devolvido = (String) grelhaEmprestimo.getValueAt(grelhaEmprestimo.getSelectedRow(), 2);
        if (devolvido.equalsIgnoreCase("DEVOLVIDO")) {
            JOptionPane.showMessageDialog(null, "Situação DEVOLVIDO não pode devolver.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        int codigo = (int) grelhaEmprestimo.getValueAt(grelhaEmprestimo.getSelectedRow(), 0);
        FrmEmprestimoDevolucao frm = new FrmEmprestimoDevolucao(this, false);
        frm.novo = false;
        frm.emprestimo_id = codigo;
        frm.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void ckDevolvidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckDevolvidosActionPerformed
        // TODO add your handling code here:
        carregarGrelha();
    }//GEN-LAST:event_ckDevolvidosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        carregarGrelha();
    }//GEN-LAST:event_formWindowActivated

    private void btnReemitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReemitirActionPerformed
        // TODO add your handling code here:        

        if (grelhaEmprestimo.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um termo pra Reemitir.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        // SE ALINHA´ESTÁ SELECIONADA CONTINUA ///////////////////////////////////
        String listagemACessorios = "";

        int emprestimo_id = (int) modeloGrelha.getValueAt(grelhaEmprestimo.getSelectedRow(), 0);
        String tipoTermo = (String) modeloGrelha.getValueAt(grelhaEmprestimo.getSelectedRow(), 2);

        Emprestimo emp = emprestimoDao.retornaPorID(emprestimo_id);
        ArrayList<Acessorio> lista = new AcessorioDao().getListagemPorEmprestimo(emprestimo_id);

        // CRIANDO OS DADOS DO TERMO ///////////////////////////////////////////        
        for (Acessorio acessorio : lista) {
            listagemACessorios = listagemACessorios + acessorio.getNomeAcessorio() + ", ";
        }
        HashMap params = new HashMap<>();
        params.put("acessorios", listagemACessorios);
        // caminho imagem

        // VERIFICANDO DE É DEVOLVIDO OU EMPRESTIMO
        if (tipoTermo.equalsIgnoreCase("EMPRESTADO")) {
            // IMPRIMIR APARELHO E CHIP
            if (emp.getCelular().getIdCelular() > 0 && emp.getChip().getIdChip() > 0) {
                imprimir.imprimirEmprestimoCelularEChip(emprestimo_id, params);
                // APENA O APARELHO    
            } else if (emp.getCelular().getIdCelular() > 0 && emp.getChip().getIdChip() <= 0) {
                imprimir.imprimirEmprestimoCelular(emprestimo_id, params);
                // APENA O CHIP   
            } else if (emp.getCelular().getIdCelular() <= 0 && emp.getChip().getIdChip() > 0) {
                imprimir.imprimirEmprestimoChip(emprestimo_id);

            }
        } else {
            params.put("observacao", emp.getObservacaoDevolucao());
            imprimir.imprimirTermoDevolucao(emprestimo_id, params);
        }

        params.clear();


    }//GEN-LAST:event_btnReemitirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmprestimoConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnReemitir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckDevolvidos;
    private javax.swing.JTable grelhaEmprestimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton radImei;
    private javax.swing.JRadioButton radLinha;
    private javax.swing.JRadioButton radNome;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
