/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import dao.AcessorioDao;
import dao.CelularDao;
import dao.ChipDao;
import dao.EmprestimoDao;
import dao.FuncionarioDao;
import dao.ImpressaoDao;
import dao.LogDao;
import dao.MotivoEmprestimoDao;
import dao.UsuarioDao;
import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Acessorio;
import modelo.Celular;
import modelo.Chip;
import modelo.Emprestimo;
import modelo.Funcionario;
import modelo.MotivoEmprestimo;
import modelo.Session;
import modelo.Usuario;
import utilidade.ValidarCampos;

/**
 *
 * @author Tony
 */
public class FrmEmprestimo extends javax.swing.JDialog {

    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    public boolean novo;
    public boolean visualizar;

    /**
     * Creates new form FrmEmprestimo
     */
    // VARAIVEIS DO FORMULARIO //
    EmprestimoDao emprestimoDao = new EmprestimoDao();
    AcessorioDao acessorioDao = new AcessorioDao();
    FuncionarioDao funcionarioDao = new FuncionarioDao();
    CelularDao celularDao = new CelularDao();
    ChipDao chipDao = new ChipDao();
    UsuarioDao usuarioDao = new UsuarioDao();
    LogDao logDao = new LogDao();
    MotivoEmprestimoDao motivoEmprestimoDao = new MotivoEmprestimoDao();

    // lista de acessorias
    List<String> acessorios = new ArrayList<>();

    // VARIAVEIS DE ID ////////////////////////////////////////////////////////
    int emprestimo_id, funcionario_id, celular_id = 0, chip_id = 0, usuario_id;
    String listagemACessorios = "";

    // CONSTRUTO DA CLASSE
    public FrmEmprestimo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtDataEmprestimo.setText(hoje());
        carregaCombobox();
        carregaComboboxMotivo();
        txtCodigo.setVisible(false);
        ckAparelho.setSelected(true);
        ckChip.setSelected(true);
        btnBuscFuncionario1.requestFocus();

    }

    // CARREGA COMBOBOX USUARIO DO SISTEMA ////////////////////////////////////
    private void carregaCombobox() {
        List<Usuario> lista = usuarioDao.getListagemAtivos();
        cboResponsavel.addItem("Selecione...");
        for (Usuario usuario : lista) {
            cboResponsavel.addItem(usuario);
            if (Session.getNome().equalsIgnoreCase(usuario.getNome())) {
                cboResponsavel.setSelectedItem(usuario);
            }
        }

    }

    // CARREGA COMBOBOX MOTIVO EMPRESTIMO ////////////////////////////////////
    private void carregaComboboxMotivo() {
        List<MotivoEmprestimo> lista = motivoEmprestimoDao.getListagem();
        cboMotivoEmprestimo.addItem("Selecione...");
        for (MotivoEmprestimo motivo : lista) {
            cboMotivoEmprestimo.addItem(motivo);

        }

    }

    // FUNCÃO DATA HOJE ////////////////////////////////////////////////////////F
    private String hoje() {
        Date data = new Date();
        return sdf.format(data);

    }

    private String patrimonioComPonto(String patrimonio) {

        String novoPatrimonio = "Sem";
        try {
            if (!patrimonio.equals("") && patrimonio.length() == 12 && !patrimonio.isEmpty()) {
                novoPatrimonio = patrimonio.substring(0, 3) + "." + patrimonio.substring(3, 6) + "." + patrimonio.substring(6, 9) + "." + patrimonio.substring(9, 12);
            }
        } catch (Exception e) {
        }

        return novoPatrimonio;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        paneAparelho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAparelho = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtImei = new javax.swing.JTextField();
        txtSerie = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnBuscaAparelho = new javax.swing.JButton();
        txtPatrimonio = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        paneFuncionario = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSetor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFuncao = new javax.swing.JTextField();
        btnBuscFuncionario1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cboResponsavel = new javax.swing.JComboBox();
        txtDataEmprestimo = new javax.swing.JFormattedTextField();
        txtDataDevolucao = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        txtProtocolo = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cboMotivoEmprestimo = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        txtChamado = new javax.swing.JTextField();
        paneComplemento = new javax.swing.JPanel();
        ckCaixa = new javax.swing.JCheckBox();
        ckManual = new javax.swing.JCheckBox();
        ckCarregador = new javax.swing.JCheckBox();
        ckAdaptador = new javax.swing.JCheckBox();
        ckFone = new javax.swing.JCheckBox();
        ckOutro = new javax.swing.JCheckBox();
        txtComplementos = new javax.swing.JTextField();
        ckCapinha = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        paneChip = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnBuscaChip = new javax.swing.JButton();
        txtChip = new javax.swing.JTextField();
        radComChip = new javax.swing.JRadioButton();
        radSemChip = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        ckVoz = new javax.swing.JCheckBox();
        ckDados = new javax.swing.JCheckBox();
        txtLinha = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtMensagemErro = new javax.swing.JLabel();
        ckAparelho = new javax.swing.JCheckBox();
        ckChip = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(222, 231, 248));
        jPanel1.setForeground(new java.awt.Color(0, 0, 204));

        paneAparelho.setBackground(new java.awt.Color(222, 231, 248));
        paneAparelho.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados do Aparelho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        paneAparelho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneAparelhoMouseClicked(evt);
            }
        });

        jLabel1.setText("Aparelho:");

        txtAparelho.setEditable(false);
        txtAparelho.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel2.setText("Marca Modelo:");

        txtMarca.setEditable(false);
        txtMarca.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel3.setText("IMEI:");

        txtImei.setEditable(false);
        txtImei.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtSerie.setEditable(false);
        txtSerie.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel11.setText("Série:");

        btnBuscaAparelho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lupa.png"))); // NOI18N
        btnBuscaAparelho.setBorder(null);
        btnBuscaAparelho.setBorderPainted(false);
        btnBuscaAparelho.setContentAreaFilled(false);
        btnBuscaAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaAparelhoActionPerformed(evt);
            }
        });

        txtPatrimonio.setEditable(false);
        txtPatrimonio.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel19.setText("Patrimonio:");

        javax.swing.GroupLayout paneAparelhoLayout = new javax.swing.GroupLayout(paneAparelho);
        paneAparelho.setLayout(paneAparelhoLayout);
        paneAparelhoLayout.setHorizontalGroup(
            paneAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAparelhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneAparelhoLayout.createSequentialGroup()
                        .addComponent(txtAparelho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10))
                    .addGroup(paneAparelhoLayout.createSequentialGroup()
                        .addComponent(txtImei, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addGroup(paneAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneAparelhoLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscaAparelho))
                    .addComponent(txtMarca))
                .addGap(13, 13, 13))
        );
        paneAparelhoLayout.setVerticalGroup(
            paneAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAparelhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(txtAparelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(txtImei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaAparelho)
                    .addComponent(jLabel19)
                    .addComponent(txtPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitulo.setBackground(new java.awt.Color(0, 51, 102));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Empréstimo de Aparelhos");
        lblTitulo.setToolTipText("");
        lblTitulo.setOpaque(true);

        paneFuncionario.setBackground(new java.awt.Color(222, 231, 248));
        paneFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados do Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        paneFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneFuncionarioMouseClicked(evt);
            }
        });

        jLabel6.setText("Nome:");

        txtNome.setEditable(false);
        txtNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel7.setText("Setor:");

        txtSetor.setEditable(false);
        txtSetor.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel8.setText("CPF:");

        txtCpf.setEditable(false);
        txtCpf.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel9.setText("RG:");

        txtRG.setEditable(false);
        txtRG.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel10.setText("Função:");

        txtFuncao.setEditable(false);
        txtFuncao.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        btnBuscFuncionario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lupa.png"))); // NOI18N
        btnBuscFuncionario1.setBorder(null);
        btnBuscFuncionario1.setBorderPainted(false);
        btnBuscFuncionario1.setContentAreaFilled(false);
        btnBuscFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscFuncionario1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 0, 51));
        jLabel21.setText("*");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 0, 51));
        jLabel23.setText("*");

        javax.swing.GroupLayout paneFuncionarioLayout = new javax.swing.GroupLayout(paneFuncionario);
        paneFuncionario.setLayout(paneFuncionarioLayout);
        paneFuncionarioLayout.setHorizontalGroup(
            paneFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneFuncionarioLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(21, 21, 21))
                    .addGroup(paneFuncionarioLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(paneFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneFuncionarioLayout.createSequentialGroup()
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNome))
                .addGroup(paneFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneFuncionarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneFuncionarioLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneFuncionarioLayout.createSequentialGroup()
                        .addComponent(txtFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSetor))
                .addContainerGap())
        );
        paneFuncionarioLayout.setVerticalGroup(
            paneFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscFuncionario1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(222, 231, 248));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Outros dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel12.setText("Data Empréstimo:");

        jLabel13.setText("Devolução:");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Nº Protocolo:");

        cboResponsavel.setMaximumRowCount(15);

        txtDataEmprestimo.setBackground(new java.awt.Color(204, 255, 204));
        try {
            txtDataEmprestimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtDataDevolucao.setBackground(new java.awt.Color(255, 204, 204));
        try {
            txtDataDevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel18.setText("Responsável:");

        try {
            txtProtocolo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 51));
        jLabel20.setText("*");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 0, 51));
        jLabel22.setText("*");

        jLabel24.setText("Motivo Empréstimo:");

        cboMotivoEmprestimo.setMaximumRowCount(15);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Chamado:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboMotivoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel20)
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChamado))
                    .addComponent(cboResponsavel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txtChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cboMotivoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel18)
                    .addComponent(cboResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        paneComplemento.setBackground(new java.awt.Color(222, 231, 248));
        paneComplemento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Complementos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        ckCaixa.setText("Caixa");
        ckCaixa.setOpaque(false);

        ckManual.setText("Manual");
        ckManual.setOpaque(false);

        ckCarregador.setText("Carregador");
        ckCarregador.setOpaque(false);

        ckAdaptador.setText("Adaptador");
        ckAdaptador.setOpaque(false);

        ckFone.setText("Fone de Ouvido");
        ckFone.setOpaque(false);

        ckOutro.setText("Outros");
        ckOutro.setOpaque(false);

        ckCapinha.setText("Capa TPU");
        ckCapinha.setOpaque(false);

        javax.swing.GroupLayout paneComplementoLayout = new javax.swing.GroupLayout(paneComplemento);
        paneComplemento.setLayout(paneComplementoLayout);
        paneComplementoLayout.setHorizontalGroup(
            paneComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneComplementoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckCaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckCarregador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckManual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckAdaptador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckFone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckCapinha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckOutro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtComplementos)
                .addContainerGap())
        );
        paneComplementoLayout.setVerticalGroup(
            paneComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneComplementoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ckCaixa)
                    .addComponent(ckCarregador)
                    .addComponent(ckManual)
                    .addComponent(ckAdaptador)
                    .addComponent(ckFone)
                    .addComponent(ckOutro)
                    .addComponent(txtComplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckCapinha))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel14.setText("Observação:");

        txtObservacao.setColumns(20);
        txtObservacao.setLineWrap(true);
        txtObservacao.setRows(5);
        jScrollPane1.setViewportView(txtObservacao);

        btnSalvar.setBackground(new java.awt.Color(153, 204, 255));
        btnSalvar.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(null);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        paneChip.setBackground(new java.awt.Color(222, 231, 248));
        paneChip.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados do Chip", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        paneChip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneChipMouseClicked(evt);
            }
        });

        jLabel16.setText(" CHIP:");

        btnBuscaChip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lupa.png"))); // NOI18N
        btnBuscaChip.setBorder(null);
        btnBuscaChip.setBorderPainted(false);
        btnBuscaChip.setContentAreaFilled(false);
        btnBuscaChip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaChipActionPerformed(evt);
            }
        });

        txtChip.setEditable(false);
        txtChip.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        buttonGroup1.add(radComChip);
        radComChip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radComChip.setForeground(new java.awt.Color(0, 51, 153));
        radComChip.setSelected(true);
        radComChip.setText("Com Chip");
        radComChip.setOpaque(false);
        radComChip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radComChipActionPerformed(evt);
            }
        });

        buttonGroup1.add(radSemChip);
        radSemChip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radSemChip.setForeground(new java.awt.Color(153, 0, 51));
        radSemChip.setText("Sem chip");
        radSemChip.setOpaque(false);
        radSemChip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radSemChipMouseClicked(evt);
            }
        });
        radSemChip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSemChipActionPerformed(evt);
            }
        });

        jLabel17.setText("Nª Linha:");

        ckVoz.setForeground(new java.awt.Color(0, 102, 0));
        ckVoz.setText("Voz");
        ckVoz.setOpaque(false);

        ckDados.setForeground(new java.awt.Color(0, 102, 0));
        ckDados.setText("Dados");
        ckDados.setOpaque(false);

        txtLinha.setEditable(false);

        javax.swing.GroupLayout paneChipLayout = new javax.swing.GroupLayout(paneChip);
        paneChip.setLayout(paneChipLayout);
        paneChipLayout.setHorizontalGroup(
            paneChipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneChipLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(radComChip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radSemChip)
                .addGap(29, 29, 29)
                .addComponent(ckVoz, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckDados)
                .addGap(44, 44, 44)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChip, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLinha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscaChip, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        paneChipLayout.setVerticalGroup(
            paneChipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneChipLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneChipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(radComChip)
                    .addComponent(radSemChip)
                    .addComponent(ckVoz)
                    .addComponent(ckDados)
                    .addComponent(jLabel16)
                    .addComponent(txtChip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(btnBuscaChip)
                    .addComponent(txtLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cancel.png"))); // NOI18N
        btnCancelar.setText("Sair");
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtCodigo.setEnabled(false);
        txtCodigo.setOpaque(false);

        txtMensagemErro.setBackground(new java.awt.Color(222, 231, 248));
        txtMensagemErro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMensagemErro.setForeground(new java.awt.Color(204, 0, 51));
        txtMensagemErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMensagemErro.setMinimumSize(new java.awt.Dimension(10, 10));
        txtMensagemErro.setOpaque(true);

        ckAparelho.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckAparelho.setForeground(new java.awt.Color(0, 0, 204));
        ckAparelho.setText("Aparelho");
        ckAparelho.setOpaque(false);
        ckAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckAparelhoActionPerformed(evt);
            }
        });

        ckChip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckChip.setForeground(new java.awt.Color(0, 0, 204));
        ckChip.setText("Chip");
        ckChip.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ckChip.setOpaque(false);
        ckChip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckChipActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("EMPRÉSTIMO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(paneAparelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paneComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(paneFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paneChip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMensagemErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ckAparelho, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ckChip, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMensagemErro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel4)
                        .addComponent(ckAparelho)
                        .addComponent(ckChip)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneAparelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneChip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaAparelhoActionPerformed
        // TODO add your handling code here:

        if (txtNome.getText().equalsIgnoreCase("")) {

            JOptionPane.showMessageDialog(this, "Funcionário não informada", null, JOptionPane.ERROR_MESSAGE);
            txtNome.setBackground(Color.YELLOW);
            return;

        } else {
            txtNome.setBackground(Color.WHITE);
        }

        int codigo = 0;
        FrmCelularConsultaRapida frm = new FrmCelularConsultaRapida(null, true);
        frm.setVisible(true);
        try {
            codigo = frm.getCodigoCelular();
            Celular c = celularDao.getPorID(codigo);
            txtAparelho.setText(c.getMarca().getCategoria().getCategoria());
            txtMarca.setText(c.getMarca().getMarca());
            txtImei.setText(c.getImei1());
            txtSerie.setText(c.getSerie());
            celular_id = c.getIdCelular();
            txtPatrimonio.setText(patrimonioComPonto(c.getPatrimonio()));
            // VERIFICA OS ACESSORIOS //////////////////////////////////////////
            if (c.isCaixa()) {
                ckCaixa.setSelected(true);

            } else {
                ckCaixa.setSelected(false);

            }

            if (c.isCarregador()) {
                ckCarregador.setSelected(true);

            } else {
                ckCarregador.setSelected(false);

            }
            if (c.isManual()) {
                ckManual.setSelected(true);

            } else {
                ckManual.setSelected(false);

            }
            if (c.isAdaptador()) {
                ckAdaptador.setSelected(true);

            } else {
                ckAdaptador.setSelected(false);

            }
            if (c.isFoneOuvido()) {
                ckFone.setSelected(true);

            } else {
                ckFone.setSelected(false);

            }

            verificarObservacaoDevolucao(c.getImei1());

        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnBuscaAparelhoActionPerformed

    // FUNÇÃO QUE VOLTA A OBSERVÇÃO NA DEVOLUÇÃO
    private void verificarObservacaoDevolucao(String imei) {

        Emprestimo emprest = emprestimoDao.retornaObservacaoDevolucao(imei);
        if (emprest != null && !emprest.getObservacaoDevolucao().equals("")) {
            txtMensagemErro.setText(emprest.getObservacaoDevolucao().trim());
        }

    }

// VEFICICA EMPRESTIMO /////////////////////////////////////////////////////
    private void verificarEmprestimo() {

        int contadorCelular = 0, contadorChip = 0;
        String mensagem = "";
        ArrayList<Emprestimo> lista = null;
        lista = emprestimoDao.getListagemEmprestimoPorNome(txtNome.getText());

        if (lista.size() > 0) {
            for (Emprestimo emp : lista) {
                if (emp.getCelular().getIdCelular() > 0) {
                    contadorCelular++;

                }
                if (emp.getChip().getIdChip() > 0) {
                    contadorChip++;
                }
            }
        } else {
            txtMensagemErro.setText("");
        }

        if (contadorCelular > 0 || contadorChip > 0) {
            mensagem = "Funcionário tem: " + contadorCelular + " celular e " + contadorChip + " chip cadastrado com emprétimo.";
            txtMensagemErro.setText(mensagem);
        }

    }


    private void btnBuscFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscFuncionario1ActionPerformed
        // TODO add your handling code here:
        int codigo = 0;
        FrmFuncionarioConsultaRapida frmConsulta = new FrmFuncionarioConsultaRapida(null, true);
        frmConsulta.setVisible(true);
        try {
            codigo = frmConsulta.getCodigoFuncionario();
            Funcionario f = funcionarioDao.getPorID(codigo);
            txtNome.setText(f.getNome());
            txtSetor.setText(f.getLocalidade().getNomeLocalidade());
            txtCpf.setText(f.getCpf());
            txtRG.setText(f.getRg());
            txtFuncao.setText(f.getCargo().getNomeCargo());
            funcionario_id = f.getIdFuncionario();

            verificarEmprestimo();
            txtNome.setBackground(Color.WHITE);
            txtSetor.setBackground(Color.WHITE);
            txtCpf.setBackground(Color.WHITE);
            txtRG.setBackground(Color.WHITE);
            txtFuncao.setBackground(Color.WHITE);

        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnBuscFuncionario1ActionPerformed

    private void btnBuscaChipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaChipActionPerformed
        // TODO add your handling code here:

        if (txtNome.getText().equalsIgnoreCase("")) {

            JOptionPane.showMessageDialog(this, "Funcionário não informada", null, JOptionPane.ERROR_MESSAGE);
            txtNome.setBackground(Color.YELLOW);
            return;

        } else {
            txtNome.setBackground(Color.WHITE);
        }

        int codigo;
        FrmChipConsultaRapida frmConsulta = new FrmChipConsultaRapida(null, true);
        frmConsulta.setVisible(true);
        try {
            codigo = frmConsulta.getCodigoChip();
            Chip chip = chipDao.getPorID(codigo);
            // radComChip.setSelected(true);
            if (chip.isIsDado()) {
                ckDados.setSelected(true);
                //ckDados.setEnabled(false);
            } else {
                ckDados.setSelected(false);
            }
            if (chip.isIsTelefonia()) {
                ckVoz.setSelected(true);
                //ckVoz.setEnabled(false);
            } else {
                ckVoz.setSelected(false);
            }
            txtChip.setText(chip.getCodigoChip());
            txtLinha.setText(chip.getNumeroLinha());
            chip_id = chip.getIdChip();
            radComChip.setSelected(true);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnBuscaChipActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:

        if (Session.getPrevilegio().equals("Consulta")) {
            JOptionPane.showMessageDialog(this, "Usuário se permissão para emprestimo.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        // VALIDAÇÃO DOS CAMPOS NECESSARIOS 
        if (!ckAparelho.isSelected() && !ckChip.isSelected()) {
            JOptionPane.showMessageDialog(this, "Informe o que será emprestado.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtNome.getText().equals("")) {
            txtNome.setBackground(Color.yellow);
            txtSetor.setBackground(Color.yellow);
            txtCpf.setBackground(Color.yellow);
            txtRG.setBackground(Color.yellow);
            txtFuncao.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Funcionario não informada", null, JOptionPane.ERROR_MESSAGE);
            txtNome.requestFocus();
            return;
        } else {
            txtNome.setBackground(Color.WHITE);
            txtSetor.setBackground(Color.WHITE);
            txtCpf.setBackground(Color.WHITE);
            txtRG.setBackground(Color.WHITE);
            txtFuncao.setBackground(Color.WHITE);
        }

        if (txtAparelho.getText().equals("") && txtProtocolo.getText().equals("")) {
            txtAparelho.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Telefone ou Chip não informada", null, JOptionPane.ERROR_MESSAGE);
            txtAparelho.requestFocus();
            return;
        }
        if (txtAparelho.getText().equals("") && ckAparelho.isSelected()) {
            txtAparelho.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Aparelho deve ser informada", null, JOptionPane.ERROR_MESSAGE);
            txtAparelho.requestFocus();
            return;
        }

        if (radComChip.isSelected() && txtChip.getText().equals("")) {
            txtChip.setBackground(Color.yellow);
            txtLinha.setBackground(Color.yellow);

            JOptionPane.showMessageDialog(this, "Chip não informada", null, JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            txtChip.setBackground(Color.WHITE);
            txtLinha.setBackground(Color.WHITE);

        }
        if (!radComChip.isSelected() && !radSemChip.isSelected()) {
            JOptionPane.showMessageDialog(this, "Informe se é COM CHIP ou SEM CHIP.", null, JOptionPane.ERROR_MESSAGE);

            return;
        }
        if (radComChip.isSelected() && !ckDados.isSelected() && !ckVoz.isSelected()) {
            JOptionPane.showMessageDialog(this, "Com chip deve informar dados ou voz \n Alterar no Cadastro do Chip.", null, JOptionPane.ERROR_MESSAGE);

            return;
        }
        if (ckOutro.isSelected() && txtComplementos.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Informe qual o outro acesssorio.", null, JOptionPane.ERROR_MESSAGE);
            ckOutro.requestFocus();
            return;
        }
        if (txtDataEmprestimo.getText().replace("/", "").trim().length() < 8) {
            JOptionPane.showMessageDialog(this, "Date emprestimo inválida.", null, JOptionPane.ERROR_MESSAGE);
            txtDataEmprestimo.setBackground(Color.yellow);
            txtDataEmprestimo.requestFocus();
            return;
        } else {
            txtDataEmprestimo.setBackground(Color.WHITE);
        }
        if (txtDataDevolucao.getText().replace("/", "").trim().length() < 8) {
            JOptionPane.showMessageDialog(this, "DATA DEVOLUÇÃO não informada.", null, JOptionPane.ERROR_MESSAGE);
            txtDataDevolucao.setBackground(Color.yellow);
            txtDataDevolucao.requestFocus();
            return;
        } else {
            txtDataDevolucao.setBackground(Color.WHITE);
        }
        if (cboResponsavel.getSelectedItem().equals("Selecione...")) {
            JOptionPane.showMessageDialog(this, "Informe responsável pelo empréstimo.", null, JOptionPane.ERROR_MESSAGE);
            cboResponsavel.setBackground(Color.yellow);
            cboResponsavel.requestFocus();
            return;
        } else {
            cboResponsavel.setBackground(Color.WHITE);
        }
        if (cboMotivoEmprestimo.getSelectedItem().equals("Selecione...")) {
            JOptionPane.showMessageDialog(this, "Informe o motivo do empréstimo.", null, JOptionPane.ERROR_MESSAGE);
            cboMotivoEmprestimo.setBackground(Color.yellow);
            cboMotivoEmprestimo.requestFocus();
            return;
        } else {
            cboMotivoEmprestimo.setBackground(Color.WHITE);
        }

        if (ValidarCampos.validarCampo(txtObservacao, "Observação")) {
            return;
        }

        if (ValidarCampos.validarCampoProtocolo(txtProtocolo, "Protocolo")) {
            return;
        }

        // FIM VALIDAÇÃO DOS CAMPOS NECESSARIOS 
        Emprestimo emprestimo = new Emprestimo();
        emprestimo.setSituacao("EMPRESTADO");
        emprestimo.setDataEmprestimo(txtDataEmprestimo.getText());
        emprestimo.setDataDevolucao(txtDataDevolucao.getText());
        emprestimo.setProtocolo(txtProtocolo.getText());
        Funcionario f = funcionarioDao.getPorID(funcionario_id);
        emprestimo.setFuncionario(f);
        Usuario u = (Usuario) cboResponsavel.getSelectedItem();
        emprestimo.setUsuario(u);
        emprestimo.setObservacao(txtObservacao.getText());
        Celular c = new Celular(celular_id);
        MotivoEmprestimo motivoEmprestimo = (MotivoEmprestimo) cboMotivoEmprestimo.getSelectedItem();
        emprestimo.setMotivoEmprestimo(motivoEmprestimo);

        emprestimo.setChamado(txtChamado.getText());

        c.setStatus("EMPRESTADO");
        c.setEstadoBem("BOM ESTADO");

        emprestimo.setCelular(c);

        Chip chip = new Chip(chip_id);

        chip.setStatus("EMPRESTADO");

        emprestimo.setChip(chip);
        // CADATRAO NOVO NO BANCO //////////////////////////////////////////////
        if (novo) {
            if (emprestimoDao.insert(emprestimo)) {
                emprestimo_id = emprestimoDao.retornaUltimoIDCadastrado();
                cadatrarAcessorio(); // cadatrar acessorios
                alterarChipBanco();
                celularDao.updateStatus(c); // MUDAR O ESTADO PARA EMPRESTADO               
                //JOptionPane.showMessageDialog(this, "Emprestimo realizado, aguarde o termo.", null, JOptionPane.INFORMATION_MESSAGE);
                logDao.insert("Novo Emprestimo, para: " + txtNome.getText() + " , aparelho: " + txtAparelho.getText() + " , imei: " + txtImei.getText() + " chip: " + txtProtocolo.getText());
                new FrmBarraProgresso(null, true).setVisible(true);
                imprimirTermo();
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar.", null, JOptionPane.ERROR_MESSAGE);
            }

            // ALTERAR CADASTRO NO BANCO ///////////////////////////////////////////
        } else {
            emprestimo.setIdEmprestimo(emprestimo_id);
            if (emprestimoDao.update(emprestimo)) {
                cadatrarAcessorio();
                celularDao.updateStatus(c); // MUDAR O ESTADO PARA EMPRESTADO                
                JOptionPane.showMessageDialog(this, "Alterado com Sucesso, reemitir termo.", null, JOptionPane.INFORMATION_MESSAGE);
                logDao.insert("Alterar Emprestimo, de: " + txtNome.getText() + " , aparelho: " + txtAparelho.getText() + " , imei: " + txtImei.getText() + " chip: " + txtProtocolo.getText());
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar.", null, JOptionPane.ERROR_MESSAGE);
            }

        }


    }//GEN-LAST:event_btnSalvarActionPerformed
    // IMPRIMIR OS TERMOS /////////////////////////////////////////////////////
    private void imprimirTermo() {
        // SE DEU TUDO CERTO IMPRIMR O TERMO ///////////////////////////////////
        HashMap params = new HashMap<>();
        // caminho imagem
        if (!listagemACessorios.equalsIgnoreCase("")) {
            listagemACessorios = listagemACessorios.substring(0, listagemACessorios.length() - 2);
            listagemACessorios = listagemACessorios + ".";
        }

        params.put("acessorios", listagemACessorios);

        if (!txtAparelho.getText().equalsIgnoreCase("") && radComChip.isSelected()) {
            new ImpressaoDao().imprimirEmprestimoCelularEChip(emprestimo_id, params);
        } else if (txtAparelho.getText().equalsIgnoreCase("") && radComChip.isSelected()) {
            new ImpressaoDao().imprimirEmprestimoChip(emprestimo_id);
        } else if (!txtAparelho.getText().equalsIgnoreCase("") && radSemChip.isSelected()) {
            new ImpressaoDao().imprimirEmprestimoCelular(emprestimo_id, params);
        }
        params.clear();

    }

// INSERINDO ACESSORIO NO BANCO ////////////////////////////////////////////////
    private void cadatrarAcessorio() {

        Celular celular = celularDao.getPorID(celular_id);

        if (celular != null) {
            if (ckCaixa.isSelected()) {
                acessorios.add(ckCaixa.getText());
                celular.setCaixa(true);
            } else {
                celular.setCaixa(false);
            }

            if (ckCarregador.isSelected()) {
                acessorios.add(ckCarregador.getText());
                celular.setCarregador(true);
            } else {
                celular.setCarregador(false);
            }

            if (ckManual.isSelected()) {
                acessorios.add(ckManual.getText());
                celular.setManual(true);
            } else {
                celular.setManual(false);
            }

            if (ckAdaptador.isSelected()) {
                acessorios.add(ckAdaptador.getText());
                celular.setAdaptador(true);
            } else {
                celular.setAdaptador(false);
            }

            if (ckFone.isSelected()) {
                acessorios.add(ckFone.getText());
                celular.setFoneOuvido(true);
            } else {
                celular.setFoneOuvido(false);
            }
            if (ckCapinha.isSelected()) {
                acessorios.add(ckCapinha.getText());
                celular.setCapinha(true);
            } else {
                celular.setCapinha(false);
            }

            if (ckOutro.isSelected()) {
                acessorios.add(txtComplementos.getText());

            } else {

            }

            // APAGA TODO ACESSORIO NO BANCO
            acessorioDao.deletePorIdEmprestimo(emprestimo_id); // APAGA OS ACESSORIOS NA TABELA ACESSORIOS
            celularDao.alterarAcessoriosEmprestadoNoCadastro(celular); // MUDA OS ACESSORIOS NO CADASTRO DO CELULAR
            // DEPOIS DE APAGADO NO BANCO
            Acessorio acess = new Acessorio();
            Emprestimo emp = new Emprestimo(emprestimo_id);
            acess.setEmprestimo(emp);

            for (String acessorio : acessorios) {
                listagemACessorios = listagemACessorios + acessorio.trim() + ", ";
                acess.setNomeAcessorio(acessorio);
                acessorioDao.insert(acess);

            }
        }
    }

    // ATUALINDO CHIP NO BANCO /////////////////////////////////////////////////
    private void alterarChipBanco() {
        Chip chip = new Chip();
        chip.setStatus("EMPRESTADO");
        chip.setIdChip(chip_id);
        if (chip_id > 0) {
            if (ckDados.isSelected()) {
                chip.setIsDado(true);
            } else {
                chip.setIsDado(false);
            }
            if (ckVoz.isSelected()) {
                chip.setIsTelefonia(true);
            } else {
                chip.setIsTelefonia(false);
            }
            chipDao.updateTipoChip(chip);
        }
    }
    // private void devolver os chip e celular da alteração ////////////////////

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limparTudo();
        novo = true;

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (!novo && emprestimo_id > 0) {

            Emprestimo emp = emprestimoDao.retornaPorID(emprestimo_id);
            ArrayList<Acessorio> lista = acessorioDao.getListagemPorEmprestimo(emprestimo_id);
            // dados do funcionario
            txtCodigo.setText(emp.getIdEmprestimo() + "");
            funcionario_id = emp.getFuncionario().getIdFuncionario();
            txtNome.setText(emp.getFuncionario().getNome());
            txtSetor.setText(emp.getFuncionario().getLocalidade().getNomeLocalidade());
            txtCpf.setText(emp.getFuncionario().getCpf());
            txtRG.setText(emp.getFuncionario().getRg());
            txtFuncao.setText(emp.getFuncionario().getCargo().getNomeCargo());
            // dados do aparelho

            if (emp.getCelular().getIdCelular() > 0) {
                celular_id = emp.getCelular().getIdCelular();
                txtAparelho.setText(emp.getCelular().getMarca().getCategoria().getCategoria());
                txtMarca.setText(emp.getCelular().getMarca().getMarca());
                txtSerie.setText(emp.getCelular().getSerie());
                txtImei.setText(emp.getCelular().getImei1());
                txtPatrimonio.setText(patrimonioComPonto(emp.getCelular().getPatrimonio()));
                btnBuscaAparelho.setEnabled(false);
                ckCaixa.setEnabled(true);
                ckCarregador.setEnabled(true);
                ckManual.setEnabled(true);
                ckAdaptador.setEnabled(true);
                ckFone.setEnabled(true);
                ckCapinha.setEnabled(true);
                ckOutro.setEnabled(true);
                txtComplementos.setEnabled(true);
                ckAparelho.setSelected(true);
                ckAparelho.setEnabled(false);

            } else {
                ckCaixa.setEnabled(false);
                ckCarregador.setEnabled(false);
                ckManual.setEnabled(false);
                ckAdaptador.setEnabled(false);
                ckFone.setEnabled(false);
                ckCapinha.setEnabled(false);
                ckOutro.setEnabled(false);
                txtComplementos.setEnabled(false);
                btnBuscaAparelho.setEnabled(true);
                ckAparelho.setSelected(false);
                ckAparelho.setEnabled(true);
            }

//            // dados do chip
            if (emp.getChip().getIdChip() <= 0) {
                radSemChip.setSelected(true);
                btnBuscaChip.setEnabled(true);
                ckChip.setSelected(false);
                ckChip.setEnabled(true);

            } else {

                if (emp.getChip().isIsDado()) {
                    ckDados.setSelected(true);
                } else {
                    ckDados.setSelected(false);
                }
                // telefonia ou voz
                if (emp.getChip().isIsTelefonia()) {
                    ckVoz.setSelected(true);
                } else {
                    ckVoz.setSelected(false);
                }
                chip_id = emp.getChip().getIdChip();
                txtChip.setText(emp.getChip().getCodigoChip());
                txtLinha.setText("");
                txtLinha.setText(emp.getChip().getNumeroLinha());

                radComChip.setSelected(true);
                btnBuscaChip.setEnabled(false);
                radComChip.setEnabled(false);
                radSemChip.setEnabled(false);
                ckChip.setSelected(true);
                ckChip.setEnabled(false);

            }

            //System.out.println(emp.getUsuario().getNome());
            cboResponsavel.getModel().setSelectedItem(emp.getUsuario());
            cboMotivoEmprestimo.getModel().setSelectedItem(emp.getMotivoEmprestimo());
            usuario_id = emp.getUsuario().getIdUsuario();
//            // DADOS DO EMPRESTIMO
            txtDataEmprestimo.setText("");
            txtDataDevolucao.setText("");
            txtDataEmprestimo.setText(emp.getDataEmprestimo());
            txtDataDevolucao.setText(emp.getDataDevolucao());
            txtChamado.setText(emp.getChamado());
            txtProtocolo.setText(emp.getProtocolo());
            txtObservacao.setText(emp.getObservacao());
            // PREENCHO OS DADOS DA COMBO DE ACESSORIOS
            for (int i = 0; i < lista.size(); i++) {
                switch (lista.get(i).getNomeAcessorio()) {
                    case "Caixa":
                        ckCaixa.setSelected(true);
                        break;
                    case "Carregador":
                        ckCarregador.setSelected(true);
                        break;
                    case "Manual":
                        ckManual.setSelected(true);
                        break;
                    case "Adaptador":
                        ckAdaptador.setSelected(true);
                        break;
                    case "Fone de Ouvido":
                        ckFone.setSelected(true);
                        break;
                    case "Capinha":
                        ckCapinha.setSelected(true);
                        break;
                    case "Capa TPU":
                        ckCapinha.setSelected(true);
                        break;
                    default:
                        break;
                }
                if (!lista.get(i).getNomeAcessorio().equals("Caixa")
                        && !lista.get(i).getNomeAcessorio().equals("Carregador")
                        && !lista.get(i).getNomeAcessorio().equals("Manual")
                        && !lista.get(i).getNomeAcessorio().equals("Adaptador")
                        && !lista.get(i).getNomeAcessorio().equals("Capa TPU")
                        && !lista.get(i).getNomeAcessorio().equals("Fone de Ouvido")) {
                    ckOutro.setSelected(true);
                    txtComplementos.setText(lista.get(i).getNomeAcessorio());

                }
            }

            btnBuscFuncionario1.setEnabled(false);

            if (visualizar) {
                btnSalvar.setEnabled(false);
            }

        }
    }//GEN-LAST:event_formWindowActivated


    private void radSemChipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radSemChipMouseClicked
        // TODO add your handling code here:.
        // TODO add your handling code here:
        if (radSemChip.isSelected()) {
            ckDados.setSelected(false);
            ckVoz.setSelected(false);
            ckDados.setEnabled(false);
            ckVoz.setEnabled(false);
            txtProtocolo.setText("");
            txtLinha.setText("");
        } else {
            ckDados.setSelected(false);
            ckVoz.setSelected(false);
        }
    }//GEN-LAST:event_radSemChipMouseClicked

    private void ckChipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckChipActionPerformed
        // TODO add your handling code here:
        if (ckChip.isSelected()) {
            bloquearLiberarCampos(paneChip, true);
            radComChip.setSelected(true);
            radSemChip.setEnabled(false);

        } else {
            bloquearLiberarCampos(paneChip, false);
            radSemChip.setSelected(true);
            radSemChip.setEnabled(true);

        }
    }//GEN-LAST:event_ckChipActionPerformed

    private void ckAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckAparelhoActionPerformed
        // TODO add your handling code here:

        if (ckAparelho.isSelected()) {

            bloquearLiberarCampos(paneAparelho, true);
            bloquearLiberarCampos(paneComplemento, true);

        } else {
            bloquearLiberarCampos(paneAparelho, false);
            bloquearLiberarCampos(paneComplemento, false);
        }
    }//GEN-LAST:event_ckAparelhoActionPerformed

    private void radComChipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radComChipActionPerformed
        // TODO add your handling code here:
        if (radComChip.isSelected()) {
            ckChip.setSelected(true);
        }

    }//GEN-LAST:event_radComChipActionPerformed

    private void radSemChipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSemChipActionPerformed
        // TODO add your handling code here:
        if (radSemChip.isSelected()) {
            ckChip.setSelected(false);
        }

    }//GEN-LAST:event_radSemChipActionPerformed

    private void paneFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneFuncionarioMouseClicked
        // TODO add your handling code here:
        if (txtNome.getText().equals("") && novo) {
            int codigo = 0;
            FrmFuncionarioConsultaRapida frmConsulta = new FrmFuncionarioConsultaRapida(null, true);
            frmConsulta.setVisible(true);
            try {
                codigo = frmConsulta.getCodigoFuncionario();
                Funcionario f = funcionarioDao.getPorID(codigo);
                txtNome.setText(f.getNome());
                txtSetor.setText(f.getLocalidade().getNomeLocalidade());
                txtCpf.setText(f.getCpf());
                txtRG.setText(f.getRg());
                txtFuncao.setText(f.getCargo().getNomeCargo());
                funcionario_id = f.getIdFuncionario();

                verificarEmprestimo();
                txtNome.setBackground(Color.WHITE);
                txtSetor.setBackground(Color.WHITE);
                txtCpf.setBackground(Color.WHITE);
                txtRG.setBackground(Color.WHITE);
                txtFuncao.setBackground(Color.WHITE);

            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_paneFuncionarioMouseClicked

    private void paneAparelhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneAparelhoMouseClicked
        // TODO add your handling code here:
        if (txtAparelho.getText().equals("") && novo) {
            if (txtNome.getText().equalsIgnoreCase("")) {

                JOptionPane.showMessageDialog(this, "Funcionário não informada", null, JOptionPane.ERROR_MESSAGE);
                txtNome.setBackground(Color.YELLOW);
                return;

            } else {
                txtNome.setBackground(Color.WHITE);
            }

            int codigo = 0;
            FrmCelularConsultaRapida frm = new FrmCelularConsultaRapida(null, true);
            frm.setVisible(true);
            try {
                codigo = frm.getCodigoCelular();
                Celular c = celularDao.getPorID(codigo);
                txtAparelho.setText(c.getMarca().getCategoria().getCategoria());
                txtMarca.setText(c.getMarca().getMarca());
                txtImei.setText(c.getImei1());
                txtSerie.setText(c.getSerie());
                celular_id = c.getIdCelular();
                txtPatrimonio.setText(patrimonioComPonto(c.getPatrimonio()));
                // VERIFICA OS ACESSORIOS //////////////////////////////////////////
                if (c.isCaixa()) {
                    ckCaixa.setSelected(true);

                } else {
                    ckCaixa.setSelected(false);

                }

                if (c.isCarregador()) {
                    ckCarregador.setSelected(true);

                } else {
                    ckCarregador.setSelected(false);

                }
                if (c.isManual()) {
                    ckManual.setSelected(true);

                } else {
                    ckManual.setSelected(false);

                }
                if (c.isAdaptador()) {
                    ckAdaptador.setSelected(true);

                } else {
                    ckAdaptador.setSelected(false);

                }
                if (c.isFoneOuvido()) {
                    ckFone.setSelected(true);

                } else {
                    ckFone.setSelected(false);

                }

                verificarObservacaoDevolucao(c.getImei1());

            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_paneAparelhoMouseClicked

    private void paneChipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneChipMouseClicked
        // TODO add your handling code here:
        if (txtChip.getText().equals("") && novo) {

            int codigo;
            FrmChipConsultaRapida frmConsulta = new FrmChipConsultaRapida(null, true);
            frmConsulta.setVisible(true);
            try {
                codigo = frmConsulta.getCodigoChip();
                Chip chip = chipDao.getPorID(codigo);
                // radComChip.setSelected(true);
                if (chip.isIsDado()) {
                    ckDados.setSelected(true);
                    //ckDados.setEnabled(false);
                } else {
                    ckDados.setSelected(false);
                }
                if (chip.isIsTelefonia()) {
                    ckVoz.setSelected(true);
                    //ckVoz.setEnabled(false);
                } else {
                    ckVoz.setSelected(false);
                }
                txtChip.setText(chip.getCodigoChip());
                txtLinha.setText(chip.getNumeroLinha());
                chip_id = chip.getIdChip();
                radComChip.setSelected(true);

            } catch (Exception e) {
            }

        }

    }//GEN-LAST:event_paneChipMouseClicked

    // FUNÇÃO LIBERA E BLOQUEIA ITEMS DOS COMPONENTES 
    public void bloquearLiberarCampos(JPanel painel, boolean acao) {
        Component[] componentes = painel.getComponents();
        for (Component componente : componentes) {
            componente.setEnabled(acao);
        }
    }

    // FUNÇÃO LIMPAR TUDO /////////////////////////////////////////////////////
    private void limparTudo() {
        txtNome.setText("");
        txtSetor.setText("");
        txtCpf.setText("");
        txtRG.setText("");
        txtFuncao.setText("");

        txtAparelho.setText("");
        txtMarca.setText("");
        txtImei.setText("");
        txtSerie.setText("");

        radComChip.setSelected(false);
        radSemChip.setSelected(false);
        ckVoz.setSelected(false);
        ckDados.setSelected(false);
        txtProtocolo.setText("");
        txtLinha.setText("");
        txtProtocolo.setText("");

        ckCaixa.setSelected(false);
        ckCarregador.setSelected(false);
        ckManual.setSelected(false);
        ckAdaptador.setSelected(false);
        ckFone.setSelected(false);
        ckOutro.setSelected(false);
        ckCapinha.setSelected(false);
        txtComplementos.setText("");

        txtDataEmprestimo.setText(hoje());
        txtDataDevolucao.setText("");
        cboResponsavel.setSelectedItem("Selecione...");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmEmprestimo dialog = new FrmEmprestimo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscFuncionario1;
    private javax.swing.JButton btnBuscaAparelho;
    private javax.swing.JButton btnBuscaChip;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboMotivoEmprestimo;
    private javax.swing.JComboBox cboResponsavel;
    private javax.swing.JCheckBox ckAdaptador;
    private javax.swing.JCheckBox ckAparelho;
    private javax.swing.JCheckBox ckCaixa;
    private javax.swing.JCheckBox ckCapinha;
    private javax.swing.JCheckBox ckCarregador;
    private javax.swing.JCheckBox ckChip;
    private javax.swing.JCheckBox ckDados;
    private javax.swing.JCheckBox ckFone;
    private javax.swing.JCheckBox ckManual;
    private javax.swing.JCheckBox ckOutro;
    private javax.swing.JCheckBox ckVoz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel paneAparelho;
    private javax.swing.JPanel paneChip;
    private javax.swing.JPanel paneComplemento;
    private javax.swing.JPanel paneFuncionario;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JRadioButton radComChip;
    private javax.swing.JRadioButton radSemChip;
    private javax.swing.JTextField txtAparelho;
    private javax.swing.JTextField txtChamado;
    private javax.swing.JTextField txtChip;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtComplementos;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataDevolucao;
    private javax.swing.JFormattedTextField txtDataEmprestimo;
    private javax.swing.JTextField txtFuncao;
    private javax.swing.JTextField txtImei;
    private javax.swing.JTextField txtLinha;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JLabel txtMensagemErro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JTextField txtPatrimonio;
    private javax.swing.JFormattedTextField txtProtocolo;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtSetor;
    // End of variables declaration//GEN-END:variables
}
