/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import dao.AcessorioDao;
import dao.CelularDao;
import dao.ChipDao;
import dao.EmprestimoDao;
import dao.FuncionarioDao;
import dao.UsuarioDao;
import java.awt.HeadlessException;

import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Acessorio;
import modelo.Celular;
import modelo.Chip;
import modelo.Emprestimo;

import modelo.Usuario;

/**
 *
 * @author Tony
 */
public class FrmEmprestimoDevolucao extends javax.swing.JDialog {

    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    public boolean novo;

    /**
     * Creates new form FrmEmprestimo
     */
    // VARAIVEIS DO FORMULARIO //
    EmprestimoDao emprestimoDao = new EmprestimoDao();
    AcessorioDao acessorioDao = new AcessorioDao();
    FuncionarioDao funcionarioDao = new FuncionarioDao();
    CelularDao celularDao = new CelularDao();
    ChipDao chipDao = new ChipDao();
    UsuarioDao usuarioDao = new UsuarioDao();

    // lista de acessorias
    List<String> acessorios = new ArrayList<>();

    // VARIAVEIS DE ID ////////////////////////////////////////////////////////
    int emprestimo_id, funcionario_id, celular_id, chip_id, usuario_id;
    String listagemACessorios = "";

    // CONSTRUTO DA CLASSE
    public FrmEmprestimoDevolucao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtDataEmprestimo.setText(hoje());

    }

    // FUNCÃO DATA HOJE ////////////////////////////////////////////////////////F
    private String hoje() {
        Date data = new Date();
        return sdf.format(data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAparelho = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        btnBuscFuncionario = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSetor = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDataEmprestimo = new javax.swing.JFormattedTextField();
        txtDataDevolucao = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        ckCaixa = new javax.swing.JCheckBox();
        ckManual = new javax.swing.JCheckBox();
        ckCarregador = new javax.swing.JCheckBox();
        ckAdaptador = new javax.swing.JCheckBox();
        ckFone = new javax.swing.JCheckBox();
        ckOutro = new javax.swing.JCheckBox();
        txtComplementos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtChip = new javax.swing.JTextField();
        radComChip = new javax.swing.JRadioButton();
        radSemChip = new javax.swing.JRadioButton();
        txtLinha = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        ckVoz = new javax.swing.JCheckBox();
        ckDados = new javax.swing.JCheckBox();
        btnCancelar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(222, 231, 248));

        lblTitulo.setBackground(new java.awt.Color(102, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Devolução de Equipamento");
        lblTitulo.setToolTipText("");
        lblTitulo.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(222, 231, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados do Aparelho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Aparelho:");

        txtAparelho.setEditable(false);
        txtAparelho.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel2.setText("Marca Modelo:");

        txtMarca.setEditable(false);
        txtMarca.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        btnBuscFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lupa.png"))); // NOI18N
        btnBuscFuncionario.setBorder(null);
        btnBuscFuncionario.setBorderPainted(false);
        btnBuscFuncionario.setContentAreaFilled(false);
        btnBuscFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAparelho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscFuncionario))
                    .addComponent(txtMarca))
                .addGap(13, 13, 13))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(txtAparelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(222, 231, 248));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados do Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel6.setText("Nome:");

        txtNome.setEditable(false);
        txtNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel7.setText("Setor:");

        txtSetor.setEditable(false);
        txtSetor.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(21, 21, 21)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSetor)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(222, 231, 248));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados do Chip", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel12.setText("Data Empréstimo:");

        jLabel13.setText("Data Devolução:");

        txtDataEmprestimo.setEditable(false);
        try {
            txtDataEmprestimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDataDevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(222, 231, 248));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Complementos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        ckCaixa.setText("Caixa");
        ckCaixa.setEnabled(false);
        ckCaixa.setOpaque(false);

        ckManual.setText("Manual");
        ckManual.setEnabled(false);
        ckManual.setOpaque(false);

        ckCarregador.setText("Carregador");
        ckCarregador.setEnabled(false);
        ckCarregador.setOpaque(false);

        ckAdaptador.setText("Adaptador");
        ckAdaptador.setEnabled(false);
        ckAdaptador.setOpaque(false);

        ckFone.setText("Fone de Ouvido");
        ckFone.setEnabled(false);
        ckFone.setOpaque(false);

        ckOutro.setText("Outros");
        ckOutro.setEnabled(false);
        ckOutro.setOpaque(false);

        txtComplementos.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckCarregador)
                    .addComponent(ckManual)
                    .addComponent(ckCaixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(ckOutro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtComplementos))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckFone)
                            .addComponent(ckAdaptador))
                        .addGap(0, 272, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckCaixa)
                    .addComponent(ckFone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckCarregador)
                    .addComponent(ckAdaptador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckManual)
                    .addComponent(ckOutro)
                    .addComponent(txtComplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setText("Observação:");

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        jScrollPane1.setViewportView(txtObservacao);

        btnSalvar.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvar.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/save.png"))); // NOI18N
        btnSalvar.setText("Confirmar Devolução");
        btnSalvar.setBorder(null);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(222, 231, 248));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados do Chip", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel16.setText(" CHIP:");

        txtChip.setEditable(false);
        txtChip.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        buttonGroup1.add(radComChip);
        radComChip.setForeground(new java.awt.Color(0, 51, 153));
        radComChip.setText("Com Chip");
        radComChip.setEnabled(false);
        radComChip.setOpaque(false);

        buttonGroup1.add(radSemChip);
        radSemChip.setForeground(new java.awt.Color(0, 51, 153));
        radSemChip.setText("Sem chip");
        radSemChip.setEnabled(false);
        radSemChip.setOpaque(false);
        radSemChip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radSemChipMouseClicked(evt);
            }
        });

        txtLinha.setEditable(false);
        try {
            txtLinha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtLinha.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel17.setText("Nª Linha:");

        ckVoz.setForeground(new java.awt.Color(0, 102, 0));
        ckVoz.setText("Voz");
        ckVoz.setEnabled(false);
        ckVoz.setOpaque(false);

        ckDados.setForeground(new java.awt.Color(0, 102, 0));
        ckDados.setText("Dados");
        ckDados.setEnabled(false);
        ckDados.setOpaque(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(radComChip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radSemChip)
                .addGap(29, 29, 29)
                .addComponent(ckVoz, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckDados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChip, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(radComChip)
                    .addComponent(radSemChip)
                    .addComponent(ckVoz)
                    .addComponent(ckDados)
                    .addComponent(jLabel16)
                    .addComponent(txtChip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscFuncionarioActionPerformed
        // TODO add your handling code here:
        int codigo = 0;
        FrmCelularConsultaRapida frm = new FrmCelularConsultaRapida(null, true);
        frm.setVisible(true);
        try {
            codigo = frm.getCodigoCelular();
            Celular c = celularDao.getPorID(codigo);
            txtAparelho.setText(c.getMarca().getCategoria().getCategoria());
            txtMarca.setText(c.getMarca().getMarca());

            celular_id = c.getIdCelular();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnBuscFuncionarioActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:

        int resposta;
        resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente Devolver ?", "", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {

            if (txtDataEmprestimo.getText().replace("/", "").trim().length() < 8) {
                JOptionPane.showMessageDialog(this, "Date emprestimo inválida.", null, JOptionPane.ERROR_MESSAGE);
                txtDataEmprestimo.requestFocus();
                return;
            }

            // FIM VALIDAÇÃO DOS CAMPOS NECESSARIOS 
            Emprestimo emprestimo = new Emprestimo(Integer.parseInt(txtCodigo.getText()));
            emprestimo.setSituacao("DEVOLVIDO");
            emprestimo.setDataDevolucao(txtDataDevolucao.getText());
            Celular celular = new Celular(celular_id);
            celular.setStatus("DEVOLVIDO");
            Chip chip = new Chip(chip_id);
            chip.setStatus("DEVOLVIDO");
            emprestimo.setObservacaoDevolucao(txtObservacao.getText());

            // CADATRAO NOVO NO BANCO //////////////////////////////////////////////
            // situacao=?, dataDevolucao=?, observacaoDevolucao = ? where idEmprestimo = ?
            if (emprestimoDao.updateDevolver(emprestimo)) {
                chipDao.updateStatus(chip);
                celularDao.updateStatus(celular);
                listarAcessoriosParaTermo();
                JOptionPane.showMessageDialog(this, "Devolvido com Sucesso !!!", null, JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar.", null, JOptionPane.ERROR_MESSAGE);
            }

        }else{
             JOptionPane.showMessageDialog(this, "Devolução Cancelada.", null, JOptionPane.ERROR_MESSAGE);
        }

        // ALTERAR CADASTRO NO BANCO ///////////////////////////////////////

    }//GEN-LAST:event_btnSalvarActionPerformed
    // INSERINDO ACESSORIO NO BANCO ////////////////////////////////////////////
    private void listarAcessoriosParaTermo() {
        if (ckCaixa.isSelected()) {
            acessorios.add(ckCaixa.getText());
        }
        if (ckCarregador.isSelected()) {
            acessorios.add(ckCarregador.getText());
        }
        if (ckManual.isSelected()) {
            acessorios.add(ckManual.getText());
        }
        if (ckAdaptador.isSelected()) {
            acessorios.add(ckAdaptador.getText());
        }
        if (ckFone.isSelected()) {
            acessorios.add(ckFone.getText());
        }
        if (ckOutro.isSelected()) {
            acessorios.add(txtComplementos.getText());
        }

        for (String acessorio : acessorios) {
            listagemACessorios = listagemACessorios + acessorio.trim() + " - ";
        }

    }


    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (!novo && emprestimo_id > 0) {

            Emprestimo emp = emprestimoDao.retornaPorID(emprestimo_id);
            ArrayList<Acessorio> lista = acessorioDao.getListagemPorEmprestimo(emprestimo_id);
            // dados do funcionario
            txtCodigo.setText(emp.getIdEmprestimo() + "");
            funcionario_id = emp.getFuncionario().getIdFuncionario();
            txtNome.setText(emp.getFuncionario().getNome());
            txtSetor.setText(emp.getFuncionario().getLocalidade().getNomeLocalidade());

            // dados do aparelho
            try {
                celular_id = emp.getCelular().getIdCelular();
                txtAparelho.setText(emp.getCelular().getMarca().getCategoria().getCategoria());
                txtMarca.setText(emp.getCelular().getMarca().getMarca());

            } catch (Exception e) {

            }
            try {
                radSemChip.setSelected(true);
            } catch (Exception e) {
            }

//            // dados do chip
            if (!emp.getChip().getNumeroLinha().equals("")) {
                radComChip.setSelected(true);
                if (emp.getChip().isIsDado()) {
                    ckDados.setSelected(true);
                } else {
                    ckDados.setSelected(false);
                }
                // telefonia ou voz
                if (emp.getChip().isIsTelefonia()) {
                    ckVoz.setSelected(true);
                } else {
                    ckVoz.setSelected(false);
                }
                chip_id = emp.getChip().getIdChip();
                txtChip.setText(emp.getChip().getCodigoChip());
                txtLinha.setText("");
                txtLinha.setText(emp.getChip().getNumeroLinha());

            }

//            // marca o combo do emprestador
            Usuario user = new UsuarioDao().getPorID(emp.getUsuario().getIdUsuario());
            //System.out.println(user.getNome());
            usuario_id = user.getIdUsuario();
//            // DADOS DO EMPRESTIMO
            txtDataEmprestimo.setText("");
            txtDataDevolucao.setText(hoje());
            txtDataEmprestimo.setText(emp.getDataEmprestimo());
            txtDataDevolucao.setText(emp.getDataDevolucao());
            txtObservacao.setText(emp.getObservacao());
            // PREENCHO OS DADOS DA COMBO DE ACESSORIOS
            for (int i = 0; i < lista.size(); i++) {
                if (lista.get(i).getNomeAcessorio().equals("Caixa")) {
                    ckCaixa.setSelected(true);
                } else if (lista.get(i).getNomeAcessorio().equals("Carregador")) {
                    ckCarregador.setSelected(true);
                } else if (lista.get(i).getNomeAcessorio().equals("Manual")) {
                    ckManual.setSelected(true);
                } else if (lista.get(i).getNomeAcessorio().equals("Adaptador")) {
                    ckAdaptador.setSelected(true);
                } else if (lista.get(i).getNomeAcessorio().equals("Fone de Ouvido")) {
                    ckFone.setSelected(true);
                }
                if (!lista.get(i).getNomeAcessorio().equals("Caixa")
                        && !lista.get(i).getNomeAcessorio().equals("Carregador")
                        && !lista.get(i).getNomeAcessorio().equals("Manual")
                        && !lista.get(i).getNomeAcessorio().equals("Adaptador")
                        && !lista.get(i).getNomeAcessorio().equals("Fone de Ouvido")) {
                    ckOutro.setSelected(true);
                    txtComplementos.setText(lista.get(i).getNomeAcessorio());

                }
            }
        }
    }//GEN-LAST:event_formWindowActivated

    private void radSemChipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radSemChipMouseClicked
        // TODO add your handling code here:.
        // TODO add your handling code here:
        if (radSemChip.isSelected()) {
            ckDados.setSelected(false);
            ckVoz.setSelected(false);
            ckDados.setEnabled(false);
            ckVoz.setEnabled(false);
            txtChip.setText("");
            txtLinha.setText("");
        } else {
            ckDados.setSelected(false);
            ckVoz.setSelected(false);
        }
    }//GEN-LAST:event_radSemChipMouseClicked

    // FUNÇÃO LIMPAR TUDO /////////////////////////////////////////////////////
    private void limparTudo() {
        txtNome.setText("");
        txtSetor.setText("");

        txtAparelho.setText("");
        txtMarca.setText("");

        radComChip.setSelected(false);
        radSemChip.setSelected(false);
        ckVoz.setSelected(false);
        ckDados.setSelected(false);
        txtChip.setText("");
        txtLinha.setText("");

        ckCaixa.setSelected(false);
        ckCarregador.setSelected(false);
        ckManual.setSelected(false);
        ckAdaptador.setSelected(false);
        ckFone.setSelected(false);
        ckOutro.setSelected(false);
        txtComplementos.setText("");

        txtDataEmprestimo.setText(hoje());
        txtDataDevolucao.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimoDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimoDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimoDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimoDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmEmprestimoDevolucao dialog = new FrmEmprestimoDevolucao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscFuncionario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckAdaptador;
    private javax.swing.JCheckBox ckCaixa;
    private javax.swing.JCheckBox ckCarregador;
    private javax.swing.JCheckBox ckDados;
    private javax.swing.JCheckBox ckFone;
    private javax.swing.JCheckBox ckManual;
    private javax.swing.JCheckBox ckOutro;
    private javax.swing.JCheckBox ckVoz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JRadioButton radComChip;
    private javax.swing.JRadioButton radSemChip;
    private javax.swing.JTextField txtAparelho;
    private javax.swing.JTextField txtChip;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtComplementos;
    private javax.swing.JFormattedTextField txtDataDevolucao;
    private javax.swing.JFormattedTextField txtDataEmprestimo;
    private javax.swing.JFormattedTextField txtLinha;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JTextField txtSetor;
    // End of variables declaration//GEN-END:variables
}
