/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import dao.CargoDao;
import dao.EmpresaDao;
import dao.EmprestimoDao;
import dao.ImpressaoDao;
import dao.LocalidadeDao;
import dao.MarcaDao;
import dao.MotivoEmprestimoDao;
import java.awt.Color;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.Cargo;
import modelo.Empresa;
import modelo.Emprestimo;
import modelo.Localidade;
import modelo.Marca;
import modelo.MotivoEmprestimo;

/**
 *
 * @author Tony
 */
public class FrmEmprestimoConsultaFiltro extends javax.swing.JFrame {

    EmprestimoDao emprestimoDao = new EmprestimoDao();
    LocalidadeDao localidadeDao = new LocalidadeDao();
    DefaultTableModel modeloGrelha;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    
    //Lista dos filtros
    ArrayList<Emprestimo> lista = null;

    /**
     * Creates new form FrmEmprestimoConsulta
     */
    public FrmEmprestimoConsultaFiltro() {
        initComponents();
        modeloGrelha = (DefaultTableModel) grelhaEmprestimoFiltro.getModel();
        this.setExtendedState(MAXIMIZED_BOTH);

        // carregando os combobox
        comboTipoLocalidade();
        comboLocalidade();
        comboModelo();
        comboMotivos();
        comboCargos();
        comboOperadoras();

    }

    // Carrega combo tipo localidade ///////////////////////////////////////////
    private void comboTipoLocalidade() {
        cboTipoLocalidade.removeAllItems();
        ArrayList<String> tiposLocalidade = new LocalidadeDao().getAllsTiposLocalidade();
        cboTipoLocalidade.addItem("TODOS");
        for (String tipo : tiposLocalidade) {
            cboTipoLocalidade.addItem(tipo);

        }
    }

    // Carrega combo  localidade ///////////////////////////////////////////
    private void comboLocalidade() {
        cboLocalidade.removeAllItems();
        ArrayList<Localidade> tiposLocalidade = new LocalidadeDao().getAllsLocalidades();
        cboLocalidade.addItem("TODOS");
        for (Localidade localidade : tiposLocalidade) {
            cboLocalidade.addItem(localidade.getNomeLocalidade());
        }
    }

    // Carrega combo tipo localidade ///////////////////////////////////////////
    private void comboModelo() {
        cboModelo.removeAllItems();
        ArrayList<Marca> marcas = new MarcaDao().getListagemLike("");
        cboModelo.addItem("TODOS");
        for (Marca marca : marcas) {
            cboModelo.addItem(marca.getMarca());
        }
    }

    // Carrega combo tipo motivos //////////////////////////////////////////////
    private void comboMotivos() {
        cboMotivo.removeAllItems();
        ArrayList<MotivoEmprestimo> motivos = new MotivoEmprestimoDao().getListagem();
        cboMotivo.addItem("TODOS");
        for (MotivoEmprestimo motivo : motivos) {
            cboMotivo.addItem(motivo.getMotivoEmprestimo());
        }
    }

    // Carrega combo tipo cargos ///////////////////////////////////////////////
    private void comboCargos() {
        cboCargo.removeAllItems();
        ArrayList<Cargo> cargos = new CargoDao().getListagemCargos();
        cboCargo.addItem("TODOS");
        for (Cargo cargo : cargos) {
            cboCargo.addItem(cargo.getNomeCargo());
        }
    }

    // Carrega combo tipo cargos ///////////////////////////////////////////////
    private void comboOperadoras() {
        cboOperadora.removeAllItems();
        ArrayList<Empresa> empresasas = new EmpresaDao().getListagemLike("");
        cboOperadora.addItem("TODOS");
        for (Empresa empresa : empresasas) {
            cboOperadora.addItem(empresa.getNomeEmpresa());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grelhaEmprestimoFiltro = new javax.swing.JTable();
        ckDevolvidos = new javax.swing.JCheckBox();
        btnLimpar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblQuantidade = new javax.swing.JLabel();
        btnExcel = new javax.swing.JButton();
        ckEmprestado = new javax.swing.JCheckBox();
        cboTipoLocalidade = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboLocalidade = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboModelo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cboMotivo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cboCargo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cboOperadora = new javax.swing.JComboBox<>();
        btnLimpar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        radNome = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        radLocalidade = new javax.swing.JRadioButton();
        radCargo = new javax.swing.JRadioButton();
        radModelo = new javax.swing.JRadioButton();
        radMotivo = new javax.swing.JRadioButton();
        lblQuantidade1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(159, 186, 213));
        jPanel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        lblTitulo.setBackground(new java.awt.Color(0, 102, 102));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Filtro Avançado do Empréstimos");
        lblTitulo.setToolTipText("");
        lblTitulo.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Seleciona Pesquisa:");

        grelhaEmprestimoFiltro.setAutoCreateRowSorter(true);
        grelhaEmprestimoFiltro.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        grelhaEmprestimoFiltro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nª", "DATA", "SITUAÇÃO", "MOTIVO", "FUNCIONÁRIO", "FUNÇÃO", "LOCALIDADE / SETOR", "APARELHO", "IMEI", "PATRIMONIO", "Nª TELEFONE", "DADOS", "VOZ", "PROTOCOLO", "DEVOLVER", "POR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grelhaEmprestimoFiltro.setRowHeight(21);
        grelhaEmprestimoFiltro.setSelectionBackground(new java.awt.Color(0, 204, 204));
        grelhaEmprestimoFiltro.getTableHeader().setReorderingAllowed(false);
        grelhaEmprestimoFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                grelhaEmprestimoFiltroMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(grelhaEmprestimoFiltro);
        if (grelhaEmprestimoFiltro.getColumnModel().getColumnCount() > 0) {
            grelhaEmprestimoFiltro.getColumnModel().getColumn(0).setPreferredWidth(40);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(0).setMaxWidth(40);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(1).setPreferredWidth(80);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(1).setMaxWidth(80);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(2).setPreferredWidth(100);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(2).setMaxWidth(100);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(3).setPreferredWidth(350);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(3).setMaxWidth(350);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(7).setPreferredWidth(190);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(7).setMaxWidth(190);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(8).setPreferredWidth(130);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(8).setMaxWidth(130);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(9).setPreferredWidth(110);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(9).setMaxWidth(110);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(10).setPreferredWidth(110);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(10).setMaxWidth(110);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(11).setPreferredWidth(60);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(11).setMaxWidth(60);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(12).setPreferredWidth(60);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(12).setMaxWidth(60);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(13).setPreferredWidth(100);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(13).setMaxWidth(100);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(14).setPreferredWidth(90);
            grelhaEmprestimoFiltro.getColumnModel().getColumn(14).setMaxWidth(90);
        }

        ckDevolvidos.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ckDevolvidos.setForeground(new java.awt.Color(153, 0, 0));
        ckDevolvidos.setText("DEVOLVIDOS");
        ckDevolvidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckDevolvidosActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(255, 204, 204));
        btnLimpar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/clearResultado.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("* EMPRESTADOS");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("*DEVOLVIDOS");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("* ATRASADOS");

        jButton1.setBackground(new java.awt.Color(255, 204, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pdf_1.png"))); // NOI18N
        jButton1.setText("PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuantidade.setForeground(new java.awt.Color(102, 0, 0));
        lblQuantidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidade.setText("0 - Empréstimo localizados");

        btnExcel.setBackground(new java.awt.Color(204, 255, 204));
        btnExcel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/xls.png"))); // NOI18N
        btnExcel.setText("EXCEL");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        ckEmprestado.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ckEmprestado.setForeground(new java.awt.Color(0, 102, 51));
        ckEmprestado.setSelected(true);
        ckEmprestado.setText("EMPRESTADO");
        ckEmprestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckEmprestadoActionPerformed(evt);
            }
        });

        cboTipoLocalidade.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        cboTipoLocalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTipoLocalidade.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboTipoLocalidadePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tipo Localidade");

        cboLocalidade.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        cboLocalidade.setMaximumRowCount(35);
        cboLocalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLocalidade.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboLocalidadePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Localidade / Setor");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Marca Modelo");

        cboModelo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        cboModelo.setMaximumRowCount(35);
        cboModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboModelo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboModeloPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Motivo");

        cboMotivo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        cboMotivo.setMaximumRowCount(25);
        cboMotivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMotivo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboMotivoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Cargo");

        cboCargo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        cboCargo.setMaximumRowCount(25);
        cboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCargo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboCargoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Operadora");

        cboOperadora.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        cboOperadora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboOperadora.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboOperadoraPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        btnLimpar1.setBackground(new java.awt.Color(153, 255, 153));
        btnLimpar1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnLimpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lupa.png"))); // NOI18N
        btnLimpar1.setText("Buscar");
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(159, 186, 213));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup3.add(radNome);
        radNome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        radNome.setSelected(true);
        radNome.setText("Nome Funcionário");
        radNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNomeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel11.setText("ORDENAR POR");

        buttonGroup3.add(radLocalidade);
        radLocalidade.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        radLocalidade.setText("Localidade");
        radLocalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radLocalidadeActionPerformed(evt);
            }
        });

        buttonGroup3.add(radCargo);
        radCargo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        radCargo.setText("Cargo");
        radCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCargoActionPerformed(evt);
            }
        });

        buttonGroup3.add(radModelo);
        radModelo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        radModelo.setText("Modelo");
        radModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radModeloActionPerformed(evt);
            }
        });

        buttonGroup3.add(radMotivo);
        radMotivo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        radMotivo.setText("Motivo");
        radMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMotivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(radNome)
                .addGap(7, 7, 7)
                .addComponent(radLocalidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radModelo)
                .addGap(4, 4, 4)
                .addComponent(radMotivo)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(radModelo)
                    .addComponent(radMotivo)
                    .addComponent(radLocalidade)
                    .addComponent(radNome)
                    .addComponent(radCargo)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        lblQuantidade1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuantidade1.setForeground(new java.awt.Color(102, 0, 0));
        lblQuantidade1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidade1.setText("0 - Empréstimo localizados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(478, 478, 478)
                        .addComponent(lblQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cboTipoLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cboLocalidade, 0, 311, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cboModelo, 0, 343, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cboMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(cboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(cboOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ckEmprestado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckDevolvidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(316, 316, 316)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(ckEmprestado)
                    .addComponent(ckDevolvidos)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cboTipoLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar1)
                    .addComponent(btnLimpar))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidade1))
                .addGap(21, 21, 21))
        );

        lblQuantidade.getAccessibleContext().setAccessibleName("0 - Empréstimo localizados.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String patrimonioComPonto(String patrimonio) {

        String novoPatrimonio = "";
        try {
            if (!patrimonio.equals("") && patrimonio.length() == 12 && !patrimonio.isEmpty()) {
                novoPatrimonio = patrimonio.substring(0, 3) + "." + patrimonio.substring(3, 6) + "." + patrimonio.substring(6, 9) + "." + patrimonio.substring(9, 12);
            }

        } catch (Exception e) {
        }

        return novoPatrimonio;

    }

    // RETORNA QUAL BOTÃO FOI SELECIONADO //////////////////////////////////////
    private String ordenarPor() {

        String ordem = "";
        if (radNome.isSelected()) {
            ordem = "nome";
        } else if (radLocalidade.isSelected()) {
            ordem = "localidade";
        } else if (radCargo.isSelected()) {
            ordem = "cargo";
        } else if (radModelo.isSelected()) {
            ordem = "modelo";
        } else if (radMotivo.isSelected()) {
            ordem = "motivo";
        }

        return ordem;
    }

    // CARREGA GRELHA CONFORME PESQUISA ////////////////////////////////////////
    private void carregarGrelha() {
        // pesquisa somente emprestados
        String soEmprestados = "";

        String tipoLocalidade = (String) cboTipoLocalidade.getSelectedItem();
        String localidade = (String) cboLocalidade.getSelectedItem();
        String modelo = (String) cboModelo.getSelectedItem();
        String motivo = (String) cboMotivo.getSelectedItem();
        String cargo = (String) cboCargo.getSelectedItem();
        String operadora = (String) cboOperadora.getSelectedItem();

        String ordenar = ordenarPor();

        if (!ckDevolvidos.isSelected()) {
            soEmprestados = "EMPRESTADO";
        } else {
            soEmprestados = "DEVOLVIDO";
        }

        if (ckDevolvidos.isSelected() && ckEmprestado.isSelected()) {
            soEmprestados = "EMPRESTADO_DEVOLVIDO";
        }

        // realiza a busca no banco
         lista = emprestimoDao.getListagemFiltro(soEmprestados, tipoLocalidade, localidade, modelo, motivo, cargo, operadora, ordenar);

        // limpa a tabela
        modeloGrelha.setNumRows(0);

        //System.out.println(lista.size());
        lista.forEach((emprestimo) -> {

            String patrimonioCorrigido = "";

            if (emprestimo.getCelular().getPatrimonio() != null) {
                patrimonioCorrigido = patrimonioComPonto(emprestimo.getCelular().getPatrimonio());
            }

            modeloGrelha.addRow(new Object[]{
                emprestimo.getIdEmprestimo(),
                emprestimo.getDataEmprestimo(),
                emprestimo.getSituacao(),
                emprestimo.getMotivoEmprestimo().getMotivoEmprestimo(),
                emprestimo.getFuncionario().getNome(),
                emprestimo.getFuncionario().getCargo().getNomeCargo(),
                emprestimo.getFuncionario().getLocalidade().getNomeLocalidade(),
                emprestimo.getCelular().getMarca().getMarca(),
                emprestimo.getCelular().getImei1(),
                patrimonioCorrigido,
                emprestimo.getChip().getNumeroLinha(),
                emprestimo.getChip().isIsDado() ? "dados" : "---",
                emprestimo.getChip().isIsTelefonia() ? "voz" : "---",
                emprestimo.getProtocolo(),
                emprestimo.getDataDevolucao(),
                emprestimo.getUsuario().getNome()
            }
            );

        });
        pinta();
        lblQuantidade.setText(modeloGrelha.getRowCount() + " - Empréstimos localizados.");
        lblQuantidade1.setText(modeloGrelha.getRowCount() + " - Empréstimos localizados.");

//        if (modeloGrelha.getRowCount() <= 0) {
//            JOptionPane.showMessageDialog(null, "Não consta registro no banco.", "Erro", JOptionPane.ERROR_MESSAGE);
//
//        }

    }

    // PINTANDO GRADE 
    private void pinta() {
        grelhaEmprestimoFiltro.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                //*******************************************
                int coluna = 2;
                int colunaDevolucao = 14;

                Object procurado = grelhaEmprestimoFiltro.getValueAt(row, coluna);

                String dataDevolucao = (String) grelhaEmprestimoFiltro.getValueAt(row, colunaDevolucao);

                Date dataDevolucaoDate = null;

                if (procurado.equals("EMPRESTADO")) {
                    label.setForeground(Color.BLACK);
                } else {
                    label.setForeground(new Color(153, 0, 1));
                }

                if (dataDevolucao.replace("/", "").length() >= 8) {
                    try {
                        dataDevolucaoDate = sdf.parse(dataDevolucao);

                        if (dataDevolucaoDate.before(new Date()) && procurado.equals("EMPRESTADO")) {

                            label.setForeground(new Color(0, 0, 156));
                        }

                    } catch (ParseException ex) {

                    }

                }

                //*******************************************
                return label;

            }
        });
    }

    //FUNÇÃO MOSTRAR APENAS ATRASADOS //////////////////////////////////////////
    private void mostraApenasAtrazados() {

        for (int i = 0; i < modeloGrelha.getRowCount(); i++) {

            String dataDelucao = (String) grelhaEmprestimoFiltro.getValueAt(i, 14);
            String emprestado = (String) grelhaEmprestimoFiltro.getValueAt(i, 2);
            Date dataDevolucaoDate = null;

            if (dataDelucao.replace("/", "").length() >= 8) {
                try {
                    dataDevolucaoDate = sdf.parse(dataDelucao);

                    if (dataDevolucaoDate.after(new Date()) && emprestado.equals("EMPRESTADO")) {

                        modeloGrelha.removeRow(i);
                    }

                } catch (ParseException ex) {

                }

            } else {
                modeloGrelha.removeRow(i);
            }

        }
    }


    private void ckDevolvidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckDevolvidosActionPerformed
        // TODO add your handling code here:
        if (ckDevolvidos.isSelected()) {

            carregarGrelha();
        } else {
            if (ckEmprestado.isSelected()) {
                carregarGrelha();
            }
        }
    }//GEN-LAST:event_ckDevolvidosActionPerformed

    private void grelhaEmprestimoFiltroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grelhaEmprestimoFiltroMouseReleased
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {

            if (grelhaEmprestimoFiltro.getSelectedRowCount() <= 0) {
                JOptionPane.showMessageDialog(null, "Selecione um Equipamento para Alteração.", null, JOptionPane.ERROR_MESSAGE);
                return;
            }

            //String devolvido = (String) grelhaEmprestimo.getValueAt(grelhaEmprestimo.getSelectedRow(), 2);
            int codigo = (int) grelhaEmprestimoFiltro.getValueAt(grelhaEmprestimoFiltro.getSelectedRow(), 0);
            FrmEmprestimo frm = new FrmEmprestimo(this, false);
            frm.novo = false;
            frm.visualizar = true;
            frm.emprestimo_id = codigo;
            frm.setVisible(true);

        }
    }//GEN-LAST:event_grelhaEmprestimoFiltroMouseReleased

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:

        ckDevolvidos.setSelected(false);
        ckEmprestado.setSelected(true);

        cboCargo.setSelectedIndex(0);
        cboLocalidade.setSelectedIndex(0);
        cboModelo.setSelectedIndex(0);
        cboMotivo.setSelectedIndex(0);
        cboOperadora.setSelectedIndex(0);
        cboTipoLocalidade.setSelectedIndex(0);

        modeloGrelha.setNumRows(0);


    }//GEN-LAST:event_btnLimparActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //new FrmBarraProgresso(null, true).setVisible(true);
        new ImpressaoDao().imprimirEmprestadosFiltro("pdf");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:

        //new FrmBarraProgresso(null, true).setVisible(true);
        new ImpressaoDao().imprimirEmprestadosFiltro("");

    }//GEN-LAST:event_btnExcelActionPerformed

    private void ckEmprestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckEmprestadoActionPerformed
        // TODO add your handling code here:
        if (ckEmprestado.isSelected()) {
            carregarGrelha();
        } else {
            if (ckDevolvidos.isSelected()) {
                carregarGrelha();
            }
        }

    }//GEN-LAST:event_ckEmprestadoActionPerformed

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
        // TODO add your handling code here:
        carregarGrelha();
    }//GEN-LAST:event_btnLimpar1ActionPerformed

    private void radModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radModeloActionPerformed
        // TODO add your handling code here:
        carregarGrelha();
    }//GEN-LAST:event_radModeloActionPerformed

    private void cboTipoLocalidadePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboTipoLocalidadePopupMenuWillBecomeInvisible
        // TODO add your handling code here:

        if (!cboTipoLocalidade.getSelectedItem().equals("TODOS")) {

            cboLocalidade.removeAllItems();
            ArrayList<Localidade> tiposLocalidade = new LocalidadeDao().getAllsLocalidadesByTipo(cboTipoLocalidade.getSelectedItem().toString());
            cboLocalidade.addItem("TODOS");
            for (Localidade localidade : tiposLocalidade) {
                cboLocalidade.addItem(localidade.getNomeLocalidade());
            }

        } else {
            comboLocalidade();
        }

        carregarGrelha();


    }//GEN-LAST:event_cboTipoLocalidadePopupMenuWillBecomeInvisible

    private void cboLocalidadePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboLocalidadePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (!cboLocalidade.getSelectedItem().equals("TODOS")) {
            Localidade local = localidadeDao.retornaPorNome(cboLocalidade.getSelectedItem().toString());
            cboTipoLocalidade.setSelectedItem(local.getTipoLocalidade());
        } else {

        }
        carregarGrelha();
    }//GEN-LAST:event_cboLocalidadePopupMenuWillBecomeInvisible

    private void radNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNomeActionPerformed
        // TODO add your handling code here:
        carregarGrelha();
    }//GEN-LAST:event_radNomeActionPerformed

    private void radLocalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLocalidadeActionPerformed
        // TODO add your handling code here:
        carregarGrelha();
    }//GEN-LAST:event_radLocalidadeActionPerformed

    private void radCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCargoActionPerformed
        // TODO add your handling code here:
        carregarGrelha();
    }//GEN-LAST:event_radCargoActionPerformed

    private void radMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMotivoActionPerformed
        // TODO add your handling code here:
        carregarGrelha();
    }//GEN-LAST:event_radMotivoActionPerformed

    private void cboModeloPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboModeloPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        carregarGrelha();
    }//GEN-LAST:event_cboModeloPopupMenuWillBecomeInvisible

    private void cboMotivoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboMotivoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        carregarGrelha();
    }//GEN-LAST:event_cboMotivoPopupMenuWillBecomeInvisible

    private void cboCargoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboCargoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        carregarGrelha();
    }//GEN-LAST:event_cboCargoPopupMenuWillBecomeInvisible

    private void cboOperadoraPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboOperadoraPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        carregarGrelha();
    }//GEN-LAST:event_cboOperadoraPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimoConsultaFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmprestimoConsultaFiltro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimpar1;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cboCargo;
    private javax.swing.JComboBox<String> cboLocalidade;
    private javax.swing.JComboBox<String> cboModelo;
    private javax.swing.JComboBox<String> cboMotivo;
    private javax.swing.JComboBox<String> cboOperadora;
    private javax.swing.JComboBox<String> cboTipoLocalidade;
    private javax.swing.JCheckBox ckDevolvidos;
    private javax.swing.JCheckBox ckEmprestado;
    private javax.swing.JTable grelhaEmprestimoFiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblQuantidade1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton radCargo;
    private javax.swing.JRadioButton radLocalidade;
    private javax.swing.JRadioButton radModelo;
    private javax.swing.JRadioButton radMotivo;
    private javax.swing.JRadioButton radNome;
    // End of variables declaration//GEN-END:variables
}
