/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import dao.LogoDao;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.Logo;

/**
 *
 * @author otoniel.aalves
 */
public class FrmLogo extends javax.swing.JFrame {

    private int imagem_id;
    LogoDao logoDao = new LogoDao();

    /**
     * Creates new form FrmLogo
     */
    public FrmLogo() {
        initComponents();
        carregaImagems();
    }

    private void carregaImagems() {
        Logo logo = logoDao.getListagem();
        if(logo !=null){
            Utilidade.ManipulaImagem.exibirImagemNoLabel(logo.getImagem1(), imagem1);
            Utilidade.ManipulaImagem.exibirImagemNoLabel(logo.getImagem2(), imagem2);
            Utilidade.ManipulaImagem.exibirImagemNoLabel(logo.getImagem3(), imagem3);
            imagem_id = logo.getIdImagem();
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        imagem1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        imagem2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        imagem3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.inactiveCaption);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Imagens par Relatórios");

        jLabel3.setText("Imagem 1:");

        imagem1.setBackground(new java.awt.Color(204, 204, 204));
        imagem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagem1.setOpaque(true);
        imagem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagem1MouseClicked(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        imagem2.setBackground(new java.awt.Color(204, 204, 204));
        imagem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagem2.setOpaque(true);
        imagem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagem2MouseClicked(evt);
            }
        });

        jLabel6.setText("Imagem 2:");

        imagem3.setBackground(new java.awt.Color(204, 204, 204));
        imagem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagem3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagem3.setOpaque(true);
        imagem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagem3MouseClicked(evt);
            }
        });

        jLabel7.setText("Imagem 3:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(imagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imagem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagem1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() >= 2) {
            try {
                JFileChooser file = new JFileChooser();
                FileNameExtensionFilter filtro = new FileNameExtensionFilter("", "jpg", "png");
                file.addChoosableFileFilter(filtro);
                file.setAcceptAllFileFilterUsed(false);
                file.setDialogType(JFileChooser.OPEN_DIALOG);
                //file.setCurrentDirectory(new File("/"));
                file.showOpenDialog(this);

                String caminhaImagem = file.getSelectedFile().getPath();

                ImageIcon icon = new ImageIcon(Utilidade.ManipulaImagem.setImagemDimensao(caminhaImagem, 700, 300));

                this.imagem1.setIcon(icon);
                this.imagem1.setText("");
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_imagem1MouseClicked

    private void imagem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagem2MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() >= 2) {
            try {
                JFileChooser file = new JFileChooser();
                FileNameExtensionFilter filtro = new FileNameExtensionFilter("", "jpg", "png");
                file.addChoosableFileFilter(filtro);
                file.setAcceptAllFileFilterUsed(false);
                file.setDialogType(JFileChooser.OPEN_DIALOG);
                //file.setCurrentDirectory(new File("/"));
                file.showOpenDialog(this);

                String caminhaImagem = file.getSelectedFile().getPath();

                ImageIcon icon = new ImageIcon(Utilidade.ManipulaImagem.setImagemDimensao(caminhaImagem, 300, 100));

                this.imagem2.setIcon(icon);
                this.imagem2.setText("");
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_imagem2MouseClicked

    private void imagem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagem3MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() >= 2) {
            try {
                JFileChooser file = new JFileChooser();
                FileNameExtensionFilter filtro = new FileNameExtensionFilter("", "jpg", "png");
                file.addChoosableFileFilter(filtro);
                file.setAcceptAllFileFilterUsed(false);
                file.setDialogType(JFileChooser.OPEN_DIALOG);
                //file.setCurrentDirectory(new File("/"));
                file.showOpenDialog(this);

                String caminhaImagem = file.getSelectedFile().getPath();

                ImageIcon icon = new ImageIcon(Utilidade.ManipulaImagem.setImagemDimensao(caminhaImagem, 300, 100));

                this.imagem3.setIcon(icon);
                this.imagem3.setText("");
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_imagem3MouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:

        Logo logo = new Logo();
        logo.setImagem1(Utilidade.ManipulaImagem.convertePanelFotoEmObjeto(imagem1));
        logo.setImagem2(Utilidade.ManipulaImagem.convertePanelFotoEmObjeto(imagem2));
        logo.setImagem3(Utilidade.ManipulaImagem.convertePanelFotoEmObjeto(imagem3));
     
        logo.setIdImagem(imagem_id);
        logoDao.update(logo);
        carregaImagems();
        JOptionPane.showMessageDialog(this, "Alterado com Sucesso.");
  
    

    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel imagem1;
    private javax.swing.JLabel imagem2;
    private javax.swing.JLabel imagem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
